### ISSUE TITLE
Clock Applet - Hoovering over timezone text, causes panel to scales beyond screen limit

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-applets#101]
When hoovering above cities the "Set..." button appears, but if the text for current time is very long, it will create a scaling issue, where the panel extends beyond the screen

https://www.youtube.com/watch?v=xb1_swNKGbI
##

**Comment by monsta** [comment]
Oh and BTW, the clock applet is from mate-panel package, not from this one.

**Comment by monsta** [comment]
@infirit: the patch from [this bug report](https://bugzilla.gnome.org/show_bug.cgi?id=553929#c4) fixed it for me, but made the calendar/locations window *hide* under any maximized windows (e.g. I have mate-terminal maximized always). If this can be corrected somehow, that patch might be acceptable. What do you think?

**Comment by raveit65** [comment]
New report for this issue at the right place.
https://github.com/mate-desktop/mate-panel/issues/594
