### ISSUE TITLE
Window-List : Implement OSX/Win7/DockBarX functionality

### ISSUE THREAD

**Issue by pquiring** [mate-desktop/mate-applets#102]
Feature request.
It would be nice if the Window-List applet had an option to pin apps and show icons without text.  This is how modern taskbars work in OSX/Win7/DockBarX/ElementaryOS etc.
Might have to create a new applet to do this.
You can view DockBarX (applet for AWN) source to see how they do it.

Big thanks!

**Comment by pquiring** [comment]
https://github.com/robint99/dock-applet
is a nice looking applet that would be nice to include into Mate.

**Comment by monsta** [comment]
Ok, so it's solved by a third-party applet. Looks nice.
