### ISSUE TITLE
man pages in man/ subfolder have same names as gnome-applet man pages

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-applets#103]
The mate-applet package ships some nice man pages for the applets shipped with mate-applets (and some more).

However, when installing them to the man1 directory, they cause a conflict with man pages from the gnome-applets page.

The question is... what to do with those man pages in mate-applets. Drop them? Rename them? ...?

Mike

**Comment by monsta** [comment]
@flexiondotorg: I think this can be used as a patch for 1.8.x in Precise PPA to fix https://bugs.launchpad.net/bugs/1396578.
