### ISSUE TITLE
New Clock applet that has the option for displaying non-local timezone

### ISSUE THREAD

**Issue by mounty1** [mate-desktop/mate-applets#112]
Feature request.

As per http://forums.mate-desktop.org/viewtopic.php?f=2&t=3305 it would be nice to have the ability to display multiple clock applets showing different timezones.  This is not the same as the ability to set the hardware clock or machine timezone via the applet, which ability already exists.  It means the ability to set the timezone used locally by a clock applet instance.
##

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
