### ISSUE TITLE
MATE really needs a printing applet

### ISSUE THREAD

**Issue by skoehler** [mate-desktop/mate-applets#121]
I'm currently using system-config-printer, which provides a printing applet (system-config-printer-applet). Obviously, this package was designed for gnome 3, and there are various issues with it. For example, the printer icon doesn't show up in the tray icons or the mate panel.

However, such an applet is not really optional. It is obligatory, at least in my case. The cups daemon is configured to use a printer on a windows server. The system-config-printer-applet asks me for the username and password. Without the applet, printing just fails. 

I could specify username and password in the cups configuration, but this is clearly not a good idea for at least two reasons:
a) the password is stored in clear text in /etc/cups/printers.conf, so anybody that has physical access to the PC can obtain my windows password
b) other users of the Linux machine should not print via my windows username but use their own windows username, if they have any

Hence, a printer applet is desperately needed.

**Comment by infirit** [comment]
Folks should use [system-config-printer](http://cyberelk.net/tim/software/system-config-printer/).
