### ISSUE TITLE
invest: Investment list window does not align properly with applet

### ISSUE THREAD

**Issue by munizao** [mate-desktop/mate-applets#124]
To reproduce: add Invest applet to a horizontal panel, somewhere near the right end of the panel.
Right click on applet, ->Preferences, add a stock, close the preferences window.
Left click on applet. If the applet is on a top panel, the Investment list window will appear all the way on the left side of the screen, far from the applet. If the applet is on a bottom panel, the investment list window will not appear at all.

The culprit appears to be applet.py, line 148:

self.applet.window.get_origin(ax, ay)

That is, it appears that the intent is to use that line to set ax and ay, and that this is not happening. (I would not expect it to be, since python doesn't work that way.)

(I mostly raise this issue because I am porting my own applet to Mate 1.8, and am having similar issues with trying to use unsupported broken gdk bindings. Which makes me wonder if using gi with GTK 2 was really a good idea, given that it was pretty explicitly unsupported. But that's enough editorializing, I guess.)
##

**Comment by munizao** [comment]
Never mind, this is fixed in the current source, I think. Sorry. I should have checked that first.

**Comment by munizao** [comment]
oops. No, it isn't.

**Comment by stevesss** [comment]
I'm having this problem. How do I fix it?

**Comment by monsta** [comment]
> Left click on applet. If the applet is on a top panel, the Investment list window will appear all the way on the left side of the screen, far from the applet. If the applet is on a bottom panel, the investment list window will not appear at all.

I can reproduce it in 1.10.

**Comment by infirit** [comment]
The main problem is the crappy gir support for Gtk+2.

**Comment by infirit** [comment]
Ok, the main problem is getting the applet's x and y coordinates. In the Gtk3 version of this applet we can use ```get_origin```. But under gtk2 this always return 0, same for ```get_position```. If I do it from idle I can at least use ```get_position``` on the ```Gtk.Window```, but nothing when I do this in the applet.

The code for this is here: https://github.com/mate-desktop/mate-applets/blob/master/invest-applet/invest/applet.py#L147

**Comment by monsta** [comment]
As of MATE 1.17, migration to GTK+3 only code is done, and so the window is properly aligned with the applet (tested with top and bottom panels).
