### ISSUE TITLE
Disappearing applets

### ISSUE THREAD

**Issue by Nichtraucher** [mate-desktop/mate-applets#125]
Hi there,

I use Mate (1.2 I believe) on Linux Mint 13 (Maya) and have a problem very much like the one that is described here: http://forums.linuxmint.com/viewtopic.php?f=46&t=74946#p440369

with the result that the applets (panels etc.) are missing.

I had a look around and it seems that this problem comes up more often and seems to appear with other versions and on other distros too - but I did not find a general solution.

I'd therefore like to report this as a bug and/or request that the mate makers comment how this issue can be resolved. Let me know if you need any further information.

cheers

**Comment by stefano-k** [comment]
MATE 1.2 is no more supported, but this issue is fixed in latest MATE releases
