### ISSUE TITLE
"Character Palette": restore popup Unicode ID like in Gnome2

### ISSUE THREAD

**Issue by ssrublev** [mate-desktop/mate-applets#126]
Hello! I have a request about the "Character Palette" applet. Previously, I have placed it in a wrong forum because I messed up the name. But now I see I should post here. Here is the link:

https://github.com/mate-desktop/mate-desktop/issues/160
(I am still unsure if I am posting to correct forum)
##

**Comment by alexsl** [comment]
I think this is charpick_applet2 from mate-applets package. Yes, you are in correct repo now, your feature request related to mate-applets.

**Comment by alexsl** [comment]
As I can see in code (charpick.c, line 498), to show unicode char name this applet should built with HAVE_GUCHARMAP defined and you need to have gucharmap installed. This applet can take unicode char name only from gucharmap.
I think this is responsibility of your package builder to build this applet with HAVE_GUCHARMAP and gucharmap as dependency. What Linux distro you use and what version?

**Comment by ssrublev** [comment]
Thank you very much for the answers!

Yes I use Fedora, but I also have Ubuntu MATE and it has the same issue. Gucharmap is installed. Distro was downloaded from ubuntu-mate.org. Here is the screenshot:

![ubuntu-mate-charpick-applet-gucharmap](https://cloud.githubusercontent.com/assets/6886166/6062939/a1d1de92-ad64-11e4-8d28-806f0130784e.png)

Later I'll check it on another Ubuntu downloaded from regular Ubuntu website where MATE was installed via apt-get.

**Comment by alexsl** [comment]
I know, I tested it on ubuntu 14.04 (but I don't use this applet, only tested). I as posted above applet must be built with HAVE_GUCHARMAP defined, then this applet can read char names from gucharmap. But package builders (ubuntu, fedora and may be other too) build this package without HAVE_GUCHARMAP.
You can try to ask package builders to rebuild it with this option.
Ubuntu-mate bug tracker is here: https://bugs.launchpad.net/ubuntu-mate

**Comment by ssrublev** [comment]
Thanks, I have posted there! https://bugs.launchpad.net/ubuntu-mate/+bug/1418627

**Comment by monsta** [comment]
Sorry guys, libgucharmap is GTK+3 only these days, so it can't be used in GTK+2 build of MATE at all.
And [MATE's fork of gucharmap](https://github.com/mate-desktop/mate-character-map) has been discontinued before 1.8 release.

@stefano-k: is there a solution for this?

**Comment by NiceandGently** [comment]
@alexsl 
sorry, i don't build a GTK2 version with a GTK3 dependency in fedora/RedHat/CentOs ;)

**Comment by alexsl** [comment]
@NiceandGently
I don't use this applet and I never try to build it. I just made a very quick look to the source code. I try to help to **ssrublev**. I still don't switch to GTK3-thinking. In my head all packages is still GTK2 :) Sorry, if my investigations was not helpful. 
I think this is very huge problem that GTK2 MATE depends on libraries which GTK2 versions not more supported and removed from Linux distros. Why MATE developers drop mate-charmap?
IMO this dependency problem (not only with this package) can kill all MATE project. I use MATE from first versions and I like MATE, but now I started to think: is my choice of MATE was correct? May be need to move to XFCE for example? Look to the problem with mate-terminal, which still can't be fixed because of dependency problems. **monsta** made a patch (many thanks to him), but this patch removed now from mate-terminal. For me best version of mate was 1.6. New, 1.8 version with new Linux distros bring a lot of problems and bugs, which no one can resolve. I think MATE project start to die :(
Sorry for this sad speech.

**Comment by ssrublev** [comment]
@alexsl , your investigations were very helpful, thank you so much! I try to solve this for years (since Gnome2 abandonement) but seeked in wrong places. The good result is that we placed the request at Ubuntu-MATE forum, and Ubuntu-MATE is what we happliy have now (took so long) after Ubuntu dropped Gnome2 and introduced Unity which was so bad.

The general thing with MATE is that we simply want continuation of Gnome2 (I also want compiz in it). I tried several GUIs, including XFCE, XFCE had some fundamental flaws I couldn't fix. Nowadays we also have Cinnamon which I find pretty good for laptops. For desktops, I still prefer MATE+Compiz, which was so good before coming of Unity. It took years to restore back to normal. I was very happy when compiz was added to Fedora+MATE, and now we also have Ubuntu+MATE+compiz which is generally a contemporary realization of Gnome2. 

It is so great MATE exists (Gnome2 was continued), I am so happy and so grateful to MATE developers. Please keep up with it.

**Comment by infirit** [comment]
@ all contributors in the MATE-project, it looks like there is a need to resurrect mate-character-map... Opinions, suggestions?

**Comment by flexiondotorg** [comment]
If it is trivial to add GTK3 support then I agree to reinstating it.

**Comment by NiceandGently** [comment]
+1

**Comment by monsta** [comment]
Resurrect the whole project or only the library that would be used by charpick applet?

BTW, we'll also need to get the latest updates from the Unicode database to be on par with upstream.

**Comment by ssrublev** [comment]
This may be a good idea, but I have to remember that this particular issue #126 deals with distro build, not mate-character-map directly. Ubuntu-MATE bug was posted (https://bugs.launchpad.net/ubuntu-mate/+bug/1418627) and recently I reminded aobut it at Facebook (https://www.facebook.com/UbuntuMATEedition/posts/488154191339426). Fedora-MATE bug was posted too (https://bugzilla.redhat.com/show_bug.cgi?id=1182668) but I was told it's imposstble to fix it because of GTK3 involvement.

**Comment by monsta** [comment]
Looking at [upstream log](https://git.gnome.org/browse/gucharmap/log), I see there weren't many changes since gnome 2 version (compared to other gnome projects): mostly translation updates and Unicode database updates. So it shouldn't be hard to keep up.

**Comment by NiceandGently** [comment]
> Fedora-MATE bug was posted too (https://bugzilla.redhat.com/show_bug.cgi?id=1182668) 

This is a report about mate-notification-daemon !!!!

**Comment by ssrublev** [comment]
Yes, you are correct, the corresponding talk took place in comments, starting from comment 23: https://bugzilla.redhat.com/show_bug.cgi?id=1182668#c23

Separate bug was not raised as the result of that talk.

**Comment by infirit** [comment]
>Resurrect the whole project or only the library that would be used by charpick applet?

Well, if it is resurrected then why leave out the ui :question:.

**Comment by monsta** [comment]
I don't mind - just asking :smile:

**Comment by infirit** [comment]
Builds and runs on both Gtk versions, https://github.com/infirit/mate-character-map/tree/reboot

The applet just needs a revert of https://github.com/mate-desktop/mate-applets/commit/c759fadd251e4a5b95e0a4b483889f654ac89d62

**Comment by NiceandGently** [comment]
A gtk3 build works well in fedora 22,
But i suggest to rename the application to mcharmap to have consistent name for directories and files.

**Comment by monsta** [comment]
Works perfectly with GTK+2 build here.
Had to resolve some conflicts during the revert. Pushed it to separate branch, https://github.com/mate-desktop/mate-applets/commit/71e1a1aed94d51a8dc3ace87b07e57deeef245a4.

Not sure if we really need to declare different API versions for GTK+2 and 3 builds of mucharmap though...

**Comment by monsta** [comment]
For those interested, Debian build files have been pushed to separate branch of ```debian-packages``` repo, https://github.com/mate-desktop/debian-packages/commit/3c4a978f94aaab4196abaf8962e54e5171e30cd8.
@flexiondotorg: will probably need to adjust package names due to version 2 of mucharmap API, but for now, it builds fine :smile:

**Comment by ssrublev** [comment]
I have got my hands on my old computer with Fedora 20 and take a screenshot of how it should be. Fedora 20 MATE was doing this correctly! 
![mate-char-applet-fedora20](https://cloud.githubusercontent.com/assets/6886166/16685225/63b645ac-4512-11e6-9cfe-d58f7ee9e339.png)

**Comment by raveit65** [comment]
And what is the different to non EOL fedora versions?

**Comment by ssrublev** [comment]
This is the topic of the thread. In F20 "Character Palette" applet shows popup saying "Insert "NAME OF THE CHAR"" (Gnome2 legacy). In current version it just says "Insert special character" — NO name of the char included.

**Comment by ssrublev** [comment]
And here is what I get in all-updated latest Fedora 24 MATE (only "Insert special character" notice without the char name): 
![2016-07-11 15-32-44](https://cloud.githubusercontent.com/assets/6886166/16730705/1a56d616-477d-11e6-97a5-52ab93c47cdc.png)

**Comment by monsta** [comment]
Now that migration to GTK+3 only build is done (as of version 1.17), this issue is solved.
Distro maintainers just need to add libgucharmap as build dependency.

**Comment by ssrublev** [comment]
Oh yes thank you pepople very much it took so long but I see this working in latest Fedora-MATE now. The character places are now too wide than before but whatever =))

**Comment by monsta** [comment]
Width might be affected by GTK+ theme - try different themes to see if anything changes.

**Comment by ssrublev** [comment]
Now I've got some problems with symbols overlapping in this palette, see screenshot:

Appears not always, can't determine the exact conditions so far.

May be (not sure) this may be related to "ACCENT" Unicode special character that brings cursor back to 1 symbol to add accent to it.

Also BTW, @raveit65 or someone, how to set week start to Monday in latest Fedora-MATE? (calendar is at screenshot). Previous fixes don't work now.
![palette-bug](https://cloud.githubusercontent.com/assets/6886166/26667705/24a12cf2-46af-11e7-817e-4c35a651467e.png)

**Comment by ssrublev** [comment]
In Fedora 23, I was told by @raveit65 here https://bugzilla.redhat.com/show_bug.cgi?id=1289436 that I have to edit file `/usr/share/i18n/locales/en_US`

But in Fedora 25 this directory is empty

**Comment by ssrublev** [comment]
Today I got the alike bug also in Ubuntu-MATE (screenshot pending).

**Comment by ssrublev** [comment]
With latest updates and coming of F26 all of the issues in Fedora (width, overlap) seem to get fixed for now.

As for setting week start to Monday in Fedora-MATE I could finally resolve this in Russian Fedora Telegram chat: I had to change LC_TIME (thanks again)
