### ISSUE TITLE
stickynotes: clicking on the icon to show the notes makes Marco crash in GTK+3 build

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-applets#128]
Virtualbox, Debian Jessie, GTK+3 build of MATE 1.9 (all from git master), GTK+ 3.14.5.

1. If any notes are shown on the screen, click on the applet's icon to hide them.
2. Click on the icon to show the notes.

Result: notes aren't shown and marco crashes.

dmesg:
```
[ 2358.389705] traps: marco[26601] trap int3 ip:7fcb6edf6d30 sp:7fff6a70df50 error:0
```

~/.xsession-errors:
```
Log level 6: The program 'marco' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 111355 error_code 2 request_code 1 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

backtrace: http://pastebin.com/sChJFtB1

**Comment by monsta** [comment]
Doesn't happen with metacity, so might be some bug in Marco.

**Comment by NiceandGently** [comment]
I got 5 applications crashed with one shot.
marco:
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/sticky-notes-crash/marco-backtrace
mate-netspeed:
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/sticky-notes-crash/mate-netspeed-applet-backtrace
notification-area:
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/sticky-notes-crash/notification-area-applet-backtrace
sticky-notes:

**Comment by monsta** [comment]
Achievement unlocked: crash 5 apps in a row with one action. :grinning:

**Comment by monsta** [comment]
Weird... the code in marco and metacity is the same in these functions... yet marco crashes and metacity doesn't.

**Comment by monsta** [comment]
Workaround: disable animations.
```
gsettings set org.mate.interface enable-animations false
```

**Comment by raveit65** [comment]
Or using compiz :smile: 
But i didn't get any abrt alarm today, only marco stops working.
Looks like this is marco releated, btw. compiz or metacity are more error tolerant with sticky note crap.
