### ISSUE TITLE
[RPMLINT] Program returns random data in a function

### ISSUE THREAD

**Issue by posophe** [mate-desktop/mate-applets#131]
I: Program returns random data in a function
E: mate-applets no-return-in-nonvoid-function command.c:223

Just means there is a missing return x in a function

**Comment by monsta** [comment]
Already fixed in https://github.com/mate-desktop/mate-applets/commit/69264b94b0cf45f58576fa35b6566ea566a47d79

Besides, why post the same issue twice? I mean https://github.com/mate-desktop/mate-applets/issues/123.

**Comment by posophe** [comment]
I didn't remember I already submitted the issue.
