### ISSUE TITLE
Clock: improve appearance, use less space on panel

### ISSUE THREAD

**Issue by n32** [mate-desktop/mate-applets#132]
Create a new display option for the clock

```
Instead of this:            Sun May 3, 12:00
Use something like this:    Sun [3] 12:00

    (where the date has a different font and color)
```

---

Visual examples:

http://www.macupdate.com/app/mac/14351/menucalendarclock-ical
![menucalendariconsmaller](https://cloud.githubusercontent.com/assets/9506804/7444569/e29f4bc2-f156-11e4-9561-d8993da715c6.gif)
##

**Comment by dnk** [comment]
Lack of time format configuration.
w/a:
object_4 is clock applet id
gsettings set org.mate.panel.applet.clock:/org/mate/panel/objects/object_4/prefs/ format custom
gsettings set org.mate.panel.applet.clock:/org/mate/panel/objects/object_4/prefs/ custom-format "%a [%d] %R"

**Comment by lukefromdc** [comment]
Clock is provided in mate-panel, not mate-applets.

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
