### ISSUE TITLE
drop docbook auto-generation comment in man pages

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-applets#138]
At the top of nearly every mate-applets man pages, there is a comment like this:

```
.\" This manpage has been automatically generated by docbook2man 
.\" from a DocBook document.  This tool can be found at:
.\" <http://shell.ipoline.com/~elmert/comp/docbook2X/> 
.\" Please send any bug reports, improvements, comments, patches, 
.\" etc. to Steve Cheng <steve@ggi-project.org>.
```

As those man pages are not auto-generate by docbook, the comment should be removed.

**Comment by NiceandGently** [comment]
patches welcome

**Comment by monsta** [comment]
@sunweaver: I'm really surprised you didn't tell us anything about missing manpages (something you've fixed in the latest Debian patch)... :confused:
