### ISSUE TITLE
weather applet prefs: should display right help section for both tabs

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-applets#143]
Ok, now that I fixed the links in https://github.com/mate-desktop/mate-applets/commit/c6337aefd28f6804712c397636a7dec5d6710683, it shows the correct Prefs help page... but still doesn't scroll down to the section related to the currently active tab. Would be nice to have that.
##

**Comment by infirit** [comment]
You need to use the ```#``` and refer to the relevant sect2 id. For example ```yelp "help:mateweather/mateweather-prefs#mateweather-metric"```.

Have a look at mate-terminal's ```terminal_util_show_help``` function for an example how it is used there.

**Comment by monsta** [comment]
Yes, I know, already fixed similar issues in a few packages... it's more a reminder than a bug report :smile:

**Comment by raveit65** [comment]
@monsta 
Do you really want to fix that?
Why not closing the report an leaving it as it is?
I don't think this is a big issue.

**Comment by monsta** [comment]
Not a big issue indeed, but why closing? I'll get to this someday.
