### ISSUE TITLE
MATE clock applet's height is inconsistent with panel height

### ISSUE THREAD

**Issue by physicsshark** [mate-desktop/mate-applets#147]
![screenshot59](https://cloud.githubusercontent.com/assets/9755486/8560997/5f15e01c-24ec-11e5-936b-5befe7d43342.png) ![screenshot58](https://cloud.githubusercontent.com/assets/9755486/8560994/56a68562-24ec-11e5-8d5a-7638bd5daa5f.png)  
Most of the time when I login, all of the applets in my panel recognize the correct height of the panel (24px for me), and load themselves accordingly.  You can see this in the screenshot on the left.

Sometimes, though, the MATE clock applet does not load itself correctly, leading to excessive padding on top of the time.  You can see this in the screenshot on the right.

This panel is oriented to be a top panel, and in the picture the panel is transparent.
However, this issue seems to occur regardless of the transparency option or gtk theme.
This issue exists for me in MATE 1.10, and has been there since at least 1.8.
The workaround seems to be to re-add the applet to the panel when this happens, or to adjust the panel height to be larger, than back to 24px.
I don't know if this issue is present at other panel heights, but 24px is exactly what I want for my screen resolution.  
This issue is one of a few blemishes on top of an otherwise beautifully designed, and beautifully functional desktop.

**Comment by physicsshark** [comment]
I haven't seen this happen since I changed my theme, so I'm thinking it might be theme dependent.

**Comment by monsta** [comment]
@raveit65: seems like theme issue indeed?

**Comment by raveit65** [comment]
not with our themes :)

**Comment by monsta** [comment]
Well I meant whether we can close it or not :smile:

**Comment by physicsshark** [comment]
I haven't seen this happen with the default MATE themes.  It happened with
the Mint-X gtk theme, and I haven't seen it since I switched to the Numix
gtk theme.

**Comment by raveit65** [comment]
hurray, mate-themes are the rule :)

**Comment by monsta** [comment]
Ok, so this is surely a theme issue.
