### ISSUE TITLE
[Feature] Search on type in menu applet

### ISSUE THREAD

**Issue by divius** [mate-desktop/mate-applets#150]
The only cool feature I lack from gnome3/cinnamon in Mate is ability to press win/super button and start typing to find a program. Would be really cool to have this thing in Mate.

**Comment by flexiondotorg** [comment]
This functionality is available by pressing Alt+F2 or using 3rd party MATE panel applets such as mintMenu or MATE Menu. Some 3rd party launchers also provide this functionality, such as Synapse.
