### ISSUE TITLE
mate-volume-control-applet first decrement is by 6 %, not 5 %

### ISSUE THREAD

**Issue by jmssil** [mate-desktop/mate-applets#152]
When scrolling with the mouse over the panel icon, the first decrement is from 100 to 94 %, instead of 95 %. From that point on it steps by 5 %.
##

**Comment by ssrublev** [comment]
Oh yes. When using vol+/vol- multimedia keys on keyboard these percentages are also strange — from 0% to 5% then to 11% then to 17% etc. 

I wish I could control this percentage and set this 5% or 4% or 3% manually.

**Comment by raveit65** [comment]
@mratajsky 
Can you please take a look at it?

**Comment by jmssil** [comment]
This issue was reported more than a year now. What riddles me the most is that this did not happen before. It seems very easy to fix, can someone please inform if this is ever to be addressed? Can I help somehow?

**Comment by monsta** [comment]
Closing, as https://github.com/mate-desktop/mate-media/issues/83 is fixed now.
