### ISSUE TITLE
Multiload: Does not remember settings

### ISSUE THREAD

**Issue by kacernator** [mate-desktop/mate-applets#155]
Multiload does not remember settings of filesystems columns which should be shown.
Also when you uncheck all filesystem columns in settings, the column "process name" from processes tab is gone and you must manualy set it back in settings to make it visible again.

**Comment by infirit** [comment]
You can not configure this in the __applet__. Do you perhaps mean ```mate-system-monitor``` which opens when you click on the applet?

If so this works for me on >= mate-system-monitor >=1.10. What version are you using and on which distro?

**Comment by kacernator** [comment]
Yes, I meant mate-system-monitor. I am using Linux Mint Mate 17.2, Mate 1.10.0

**Comment by monsta** [comment]
Then the bug should be opened in https://github.com/mate-desktop/mate-system-monitor/issues instead.
