### ISSUE TITLE
New feature : locking the menus and the applets

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-applets#158]
I install Linux Mint MATE in associations. I've got a big problem : some people in the associations sometimes remove the applets, even the menus !
It is very problematic. Would it be possible to add an option that asks the admin password to lock/unlock an applet ? (using the right-click and red cross)

**Comment by infirit** [comment]
https://github.com/mate-desktop/mate-panel/issues/345#issuecomment-136380600

**Comment by Petrouchka** [comment]
It would be interesting to ask admin password only for menu removing. It's impossible to remove menus on others systems (Windows, Mac OS X, ReactOS...) and it's normal. In MATE, a normal user can easily remove it.
