### ISSUE TITLE
Window list panel applet - needs options regarding flashing

### ISSUE THREAD

**Issue by KupoMarianne** [mate-desktop/mate-applets#16]
When a window wants to get attention, its button will flash (well, pulsate) in the panel window list about five times before staying a steady colour. However, for me this isn't as useful as it could be, given my disabilities (which involve problems related to sensory processing). I would like to request a new feature, where in the options for the window list applet, a checkbox or pair of radio buttons could be set to allow windows that are trying to get attention to keep flashing/pulsating indefinitely, rather than stopping after a set number of flashes as currently happens, as this would really help anyone with disabilities similar to mine, or various other disabilities such as visual impairments (and may also be preferable to some non-disabled people too) - flashing/pulsating for longer would give me a better chance of noticing that the window wants attention. Another option which would be helpful is control over the speed of the flashing/pulsating. Thanks! :)

**Comment by monsta** [comment]
That's not possible at our level... you'll have to ask ```libwnck``` developers to add an option for this.
Currently the [tasklist properties](https://developer.gnome.org/libwnck/stable/WnckTasklist.html#WnckTasklist--s-fade-loop-time) don't allow this.
