### ISSUE TITLE
Launcher - change tab order of controls

### ISSUE THREAD

**Issue by ospyros** [mate-desktop/mate-applets#162]
Hello,

and thanks for the wonderful work on mate and mate-applets. Not sure this is the right repository to report this issue, apologies if I should address it elsewhere.

My issue is the following:

 When trying to search for an application with a launcher there might be two or three options matching. 
The problem is I can not quickly move to the application either with a list with the 'tab' key (which will take me through the up-down button,  'run in terminal', 'run with file', "show list of known applications" then to the list of matches) or a shortcut. 

The fastest way through shortcuts I think is to press ctrl+a twice (first time the list collapses then it expands) then tab.

It is just a nuance but since the whole idea of the launcher is to speed things up it might be worth considering for a future release.

Thanks again,

Spyros
##

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
