### ISSUE TITLE
Mate command applet problem

### ISSUE THREAD

**Issue by fennectech** [mate-desktop/mate-applets#163]
I use the mate command applet to fetch my ip from ifconfig.me   however it fowls up the applet and locks it up  sometimes bringing the panel down with it.
setps to reproduce
1 set command to curl ifconfig.me
##

**Comment by fennectech** [comment]
https://screencloud.net/v/bT9l    at screenshot by a friend who reproduced it on their machine

**Comment by flexiondotorg** [comment]
@stefano-k could you look at this one please?

**Comment by monsta** [comment]
The command is executed synchronously, so it's no wonder such things happen. However, there's no appropriate ```g_spawn_*``` API for running a process *and* getting its output.

I think we can use async functions of [GSubprocess](https://developer.gnome.org/gio/stable/GSubprocess.html) instead - but then we'll need to decide on setting the minimum GLib version to 2.40.

**Comment by monsta** [comment]
Oops

**Comment by stefano-k** [comment]
Or keep ```g_spawn_*``` for old glib versions

**Comment by monsta** [comment]
We can't keep ```g_spawn_command_line_sync``` as it blocks, and I couldn't find any async function that would invoke a callback on read completion...

**Comment by fennectech** [comment]
has this been patched yet?

**Comment by monsta** [comment]
No, I didn't have enough time to finish it for 1.14. Will do for 1.16.

**Comment by fennectech** [comment]
okay   thanks     there is also an issue on one of my machines that i think
may be related   i have another website that i poll    and the command
applet lags and appears frozen for seconds to minutes     usually when the
network is down this occors.   is it possable  to make an applet that just
has one purpous    aquiring and displaying the public ip's?

On Mon, Apr 18, 2016 at 6:26 AM, monsta <notifications@github.com> wrote:

> No, I didn't have enough time to finish it for 1.14. Will do for 1.16.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mate-desktop/mate-applets/issues/163#issuecomment-211337888>
>



-- 
Fennec

**Comment by monsta** [comment]
We have enough work here already, but any 3rd party developers are free to write any applets.

**Comment by johrpan** [comment]
@monsta Will you have time to work on that or have already started? If not I would like to implement that. I would just use g_shell_parse_argv () and g_spawn_async_with_pipes ().

**Comment by johrpan** [comment]
Ah, wait, the problem is to get to know when it finishes, right? So I would actually use GSubprocess then. But I won't start until I got to know whether nobody is working on that.

**Comment by monsta** [comment]
Well, I need to find some time to get back to it and finish it. Hope to get it done before 1.16 release.
You can check the current (unfinished) work at https://github.com/mate-desktop/mate-applets/commit/892025ef4e2552e5b9a1dcd7188e91aa3fc1d348.

**Comment by johrpan** [comment]
@monsta Ok, so you already do it, I just wanted to ask.

**Comment by monsta** [comment]
Sorry, didn't make it in time :disappointed: 
Hoping for 1.18.

**Comment by lukefromdc** [comment]
OK, I have it locking up the applet but not the panel after showing an IP address once

**Comment by raveit65** [comment]
fixed
https://github.com/mate-desktop/mate-applets/commit/b1006a885a586233e2cc682f4c86d569d7398306
https://github.com/mate-desktop/mate-applets/commit/da78059c5598bdf66828edd1081d3c1ca0f4805b
