### ISSUE TITLE
Workspace applet and Metacity

### ISSUE THREAD

**Issue by BartekChom** [mate-desktop/mate-applets#165]
On MATE 1.10.2 with Metacity 3.17.2 (UbuntuMATE 15.10), I get dumbed-down interface of Workspace Switcher Preferences, as in [this thread on the Mate forum](http://forums.mate-desktop.org/viewtopic.php?p=10004#p10004). When I turn on Marco, I get full interface. (I am afraid of the system hanging with Marco (is it [this bug?](https://bugs.launchpad.net/ubuntu/+source/marco/+bug/1495313)))

I have already a workaround from [another question about workspaces](http://askubuntu.com/questions/476296/i-cant-add-work-areas-in-gnome-flashback-ubuntu-14-04-or-make-the-alt-tab-work#503743): `dconf write /org/gnome/desktop/wm/preferences/num-workspaces 8` will for example create 8 workspaces.

However, it would be nice, if the preferences for the applet worked also with Metacity.
##

**Comment by raveit65** [comment]
I don't think that it is possible to use double gsettings keys for it, btw. the applet will crash if metacity isn't installed.
Btw. i don't see that my system hangs with marco, of course i use fedora.

**Comment by raveit65** [comment]
Btw, your mentioned ubuntu report is fixed.
So can we close the report?

**Comment by BartekChom** [comment]
I hoped that it will be easy for the applet to recognise the used display manager (you seem to use wnck_screen_get_window_manager_name() in mate-panel/applets/wncklet/workspace-switcher.c for it).

If you think that MATE need not to work smoothly with Metacity, I cannot demand it. It is not a big problem for me anyway. I can also try to do it myself, if you do not have time.

I start checking whether all my computers work with Marco if you are interested in it.

**Comment by raveit65** [comment]
> If you think that MATE need not to work smoothly with Metacity, I cannot demand it.

I don't think that, but we are a small team, and an application which is not updated in major distros have a middle priority for me, ie. in fedora (home of gnome/gtk+  development) metacity use version 1.12.x and will slowly die.
But if you have spare time a PR is welcome.

**Comment by BartekChom** [comment]
> I can also try to do it myself, if you do not have time.
I did not do it. It was not so easy as I thought.

> I start checking whether all my computers work with Marco if you are interested in it.
It seems that all my computers work with Marco without problems.

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
