### ISSUE TITLE
merge mate-netspeed into mate-applets

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-applets#167]
@flexiondotorg @clefebvre @raveit65 @posophe @willysr @obache 

Well, some of you already know about this idea (or even suggested it in the first place). :smile:

So I think we can do it for 1.14 release.

It will require some changes at transifex... I'm not sure if it's possible to merge translations there somehow, so probably we'll have to make an announcement there, asking everybody to re-apply their ```mate-netspeed``` translations in ```mate-applets``` project (after we upload the new ```.pot``` file there of course).

**Comment by posophe** [comment]
Great ! Finally ;-)

**Comment by raveit65** [comment]
mate-sensor-applet should move too ;)

**Comment by willysr** [comment]
+1 :)
less package to maintain

**Comment by obache** [comment]
+1
no heavy extra dependencies

**Comment by monsta** [comment]
There we go, you can test https://github.com/mate-desktop/mate-applets/pull/168 :smile:
