### ISSUE TITLE
GTK3: regression with stickynotes

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-applets#170]
After fixing deprecated gtk_icon_size_register with https://github.com/mate-desktop/mate-applets/commit/d916ca590d2d325575d197ff2227c3d0df915cd5
some stickynotes button icons are gone.
The solution is here https://git.gnome.org/browse/gnome-applets/commit/?id=76982eb73ce1bd912cc19a55d3b6682b9da93687
Unfortunately this will break gtk2 build. I need a bit help to adjust this fix.

**Comment by tarakbumba** [comment]
Didn't this fixed by https://github.com/mate-desktop/mate-applets/commit/4a9c10288ab7dcd26c667c5d8fefbbc44e8c4cf3 ?

**Comment by raveit65** [comment]
Yes :)
thanks for the reminder.
