### ISSUE TITLE
nm-applet: multiple vpn connections not possible

### ISSUE THREAD

**Issue by dyasny** [mate-desktop/mate-applets#176]
With multiple VPN definitions in NM (vpnc, openvpn, etc) it isn't possible to start more than a single vpn. As soon as one is connected, all others are greyed out. 

This is not the case with gnome 2 or 3, and there shouldn't be such a limitation from the base OS POV

versions:
Linux xxxxx 4.2.8-200.fc22.x86_64 #1 SMP Tue Dec 15 16:50:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qa |grep -i mate
mate-notification-daemon-1.12.1-1.fc22.x86_64
mate-themes-extras-3.16.3-2.fc22.noarch
mate-menus-libs-1.12.0-2.fc22.x86_64
mate-terminal-1.12.1-1.fc22.x86_64
mate-session-manager-1.12.1-1.fc22.x86_64
mate-system-monitor-1.12.1-1.fc22.x86_64
mate-themes-1.12.1-1.fc22.noarch
mate-control-center-filesystem-1.12.0-2.fc22.x86_64
mate-search-tool-1.12.0-1.fc22.x86_64
mate-control-center-1.12.0-2.fc22.x86_64
mate-backgrounds-1.12.0-1.fc22.noarch
mate-icon-theme-1.12.0-1.fc22.noarch
mate-panel-1.12.1-1.fc22.x86_64
mate-screensaver-1.12.0-1.fc22.x86_64
mate-disk-usage-analyzer-1.12.0-1.fc22.x86_64
libmateweather-1.12.1-1.fc22.x86_64
mate-system-log-1.12.0-1.fc22.x86_64
mate-polkit-1.12.0-1.fc22.x86_64
mate-utils-common-1.12.0-1.fc22.noarch
libmatekbd-1.12.1-1.fc22.x86_64
mate-settings-daemon-1.12.1-1.fc22.x86_64
mate-desktop-1.12.1-1.fc22.x86_64
mate-screenshot-1.12.0-1.fc22.x86_64
f22-backgrounds-mate-22.1.0-1.fc22.noarch
libmateweather-data-1.12.1-1.fc22.noarch
libmatemixer-1.12.1-1.fc22.x86_64
mate-media-1.12.1-1.fc22.x86_64
mate-user-guide-1.12.0-1.fc22.noarch
mate-calc-1.8.0-3.fc22.x86_64
mate-dictionary-1.12.0-1.fc22.x86_64
mate-desktop-libs-1.12.1-1.fc22.x86_64
mate-applets-1.12.1-1.fc22.x86_64
mate-menus-1.12.0-2.fc22.x86_64
mate-panel-libs-1.12.1-1.fc22.x86_64
mate-power-manager-1.12.1-1.fc22.x86_64

**Comment by raveit65** [comment]
I do not see why Mate should limited vpn connection in nm-applet, which is not a Mate application.

**Comment by dyasny** [comment]
I don't know for sure where it gets limited, but it does grey out everything as soon as there is a single connection established. I can of course still open connections via the CLI, but that's not the point. Also, if I re-login into gnome3, I don't have this problem at all, which leads me to localizing this to something to do with MATE. If there's any additional information required, please let me know

**Comment by raveit65** [comment]
Are those packages installed?
network-manager-applet
NetworkManager-adsl
NetworkManager-bluetooth
NetworkManager-l2tp
NetworkManager-openconnect
NetworkManager-iodine-gnome
NetworkManager-openswan-gnome
NetworkManager-openvpn-gnome
NetworkManager-pptp-gnome
NetworkManager-vpnc-gnome

As is said in forum gnome-shell don't use nm-applet, gnome-shell has an own internal applet.
So, you can't compare gnome3 with Mate.
For verifing you can test nm-applet in xfce.

**Comment by dyasny** [comment]
NetworkManager-l2tp-0.9.8.7-3.fc22.x86_64
NetworkManager-openvpn-gnome-1.0.6-3.fc22.x86_64
NetworkManager-glib-1.0.6-8.fc22.x86_64
NetworkManager-openswan-gnome-1.0.6-2.fc22.x86_64
NetworkManager-wwan-1.0.6-8.fc22.x86_64
NetworkManager-1.0.6-8.fc22.x86_64
NetworkManager-bluetooth-1.0.6-8.fc22.x86_64
NetworkManager-team-1.0.6-8.fc22.x86_64
NetworkManager-iodine-gnome-0.0.5-2.fc22.x86_64
NetworkManager-wifi-1.0.6-8.fc22.x86_64
NetworkManager-vpnc-1.0.6-3.fc22.x86_64
NetworkManager-libnm-1.0.6-8.fc22.x86_64
NetworkManager-vpnc-gnome-1.0.6-3.fc22.x86_64
NetworkManager-pptp-1.1.0-1.20150428git695d4f2.fc22.x86_64
NetworkManager-pptp-gnome-1.1.0-1.20150428git695d4f2.fc22.x86_64
NetworkManager-openswan-1.0.6-2.fc22.x86_64
NetworkManager-openconnect-1.0.2-1.fc22.x86_64
NetworkManager-iodine-0.0.5-2.fc22.x86_64
NetworkManager-glib-1.0.6-8.fc22.i686
NetworkManager-openvpn-1.0.6-3.fc22.x86_64
NetworkManager-adsl-1.0.6-8.fc22.x86_64

I'm not comparing, just pointing out the difference between the two desktops I use. 

If this is a problem with a package outside Mate, where should I file the BZ?

**Comment by raveit65** [comment]
Package list looks good.
[rave@mother ~]$ rpm -qa network-manager-applet
network-manager-applet-1.0.6-5.fc22.x86_64
This is the right component.
Personal i do not use a vpn connecting so it seems to be a good idea to file out a BZ to  see what NetworkManager folks thinks about.
I will leave this report a while open, please link the BZ to this one.

**Comment by dyasny** [comment]
Done: https://bugzilla.redhat.com/show_bug.cgi?id=1295955

**Comment by monsta** [comment]
Hmm... do we need to leave this open? It's not our applet :smile:

**Comment by raveit65** [comment]
not really

**Comment by raveit65** [comment]
We will re-open the report if nm-applet maintainer says it is Mate related.
Btw. you can verify that if starting another desktop like xfce or lxde which use the same applet.

**Comment by dyasny** [comment]
I tried with Cinnamon, it worked there. If I install xfce or lxde, I'll update the results here

**Comment by raveit65** [comment]
As far i know cinnamon use it's own applet, same as gnome-shell.
