### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by City-busz** [mate-desktop/mate-applets#183]
Currently the Command and Timer applets are licensed under GPL-3+, but the rest of the code is under GPL-2+. The COPYING file contains the GPL-2+ license only.

@stefano-k, is it possible to re-license Command and Timer applets under GPL-2+?

**Comment by stefano-k** [comment]
@City-busz yes, I agree

**Comment by City-busz** [comment]
Thanks! The applets are licensed under GPL-2+ now.
