### ISSUE TITLE
weather app radar doesn't show

### ISSUE THREAD

**Issue by bomull** [mate-desktop/mate-applets#190]
Neither of the available Berlin, Germany, weather stations show a radar. Version is mate-applets (1.12.1-1), the current ubuntu mate 16.04 version
##

**Comment by Bill-MI** [comment]
Here's a good clue regarding this.  Hope this helps someone...

I'm pretty sure no location from the built-in list works, I tried several in the USA.  Yet a custom URL (animated GIF) I've been using for years works fine.  Be sure to update to see results.

Also, my old Ubuntu-Mate unofficial 14.04 install has the exact same condition.

This indicates the applet itself is probably ok and something is likely bad with the online radar service.

**Comment by monsta** [comment]
Ok, I guess we can close this then?
https://forums.linuxmint.com/viewtopic.php?f=206&t=222721 is marked as solved already...

**Comment by SYN-cook** [comment]
@bomull (and other German users who happen to read this): you could use this address 
http://www.dwd.de/DWD/wetter/radar/radfilm_brd_akt.gif

**Comment by raveit65** [comment]
thx :)
