### ISSUE TITLE
Bad Venezuelan time

### ISSUE THREAD

**Issue by simonorono** [mate-desktop/mate-applets#195]
Recently I noticed that MATE clock applet was not displaying Venezuelan weather.

![screenshot at 2016-06-25 09-31-13](https://cloud.githubusercontent.com/assets/12176276/16356997/9eb2ce96-3ab3-11e6-8fc0-07ca61f34e9d.png)

Trying to check for the problem myself, I found that the timezone for Venezuela is incorrect (it was changed recently)

![screenshot at 2016-06-25 09-31-26](https://cloud.githubusercontent.com/assets/12176276/16356998/b9866dcc-3ab3-11e6-8a4e-6c7f7b90be04.png)

There it says `-4:30`, but now it is `-4:00`

However, the time displayed is correct. Is this a MATE problem or do you read that timezone information from elsewhere? Is this the reason for not displaying weather information?

I'm using Manjaro Linux current, and here's the MATE information:

![screenshot at 2016-06-25 09-38-34](https://cloud.githubusercontent.com/assets/12176276/16357018/7c835326-3ab4-11e6-9bcc-c1d1b511f5b8.png)
![screenshot at 2016-06-25 09-39-24](https://cloud.githubusercontent.com/assets/12176276/16357020/88fd65ba-3ab4-11e6-9df5-8d420ede9e1a.png)

**Comment by monsta** [comment]
Weird...
There's also a separate weather applet available in mate-applets, can you try it?

**Comment by simonorono** [comment]
Tried. The problem is when La Chinita airport is selected. It happens with some others.
![screenshot at 2016-06-26 07-01-37](https://cloud.githubusercontent.com/assets/12176276/16361865/d1cb0668-3b67-11e6-8278-8fdc8bfe4105.png)
![screenshot at 2016-06-26 07-01-47](https://cloud.githubusercontent.com/assets/12176276/16361866/d1ce1d76-3b67-11e6-9e16-3c689307a809.png)

Where does MATE get this information?

**Comment by monsta** [comment]
This is really weird. I've looked at the countries list in that Edit Location dialog, and I see -4:30 for Venezuela as well... and this is on several machines where tzdata is updated to the latest version.

Both applets get the timezone info from libmateweather (from [this huge file](https://raw.githubusercontent.com/mate-desktop/libmateweather/master/data/Locations.xml.in)), the timezone is named America/Caracas there. I have no idea why the result is different from -4:00 (which is stored in tzdata).

**Comment by simonorono** [comment]
Today, I see the temperature once again. The timezone is still listed as -4:30. The temperature issue was probably a problem with the service used for fetching that data.

![screenshot at 2016-06-27 11-01-33](https://cloud.githubusercontent.com/assets/12176276/16384399/81089b8c-3c52-11e6-9029-53ca02ae0e62.png)

![screenshot at 2016-06-27 11-03-02](https://cloud.githubusercontent.com/assets/12176276/16384414/8c0b8f1c-3c52-11e6-917f-6ef59986d636.png)

**Comment by monsta** [comment]
I finally see this fixed in my Debian Testing here. It shows GMT-4 now. Does the issue still happen for you?

**Comment by monsta** [comment]
I also see this is fixed in older system (Mint 18.1) with older MATE release (1.16), so it must be something in the system instead of our libraries/applets.

**Comment by monsta** [comment]
I guess we can close it. We can reopen it if the problem reappears.
