### ISSUE TITLE
Weather applet: Temperature for the Hague is wrong

### ISSUE THREAD

**Issue by Thomas-N** [mate-desktop/mate-applets#199]
The weather app keeps saying it's 5°C in the Hague, even when it was over 20°.

**Comment by monsta** [comment]
Do you mean the weather applet, or the weather display in the clock applet?
Or do they both have this issue?

**Comment by Thomas-N** [comment]
Both. I guess they get their info from the same source.

**Comment by monsta** [comment]
Yes, they both use [libmateweather](https://github.com/mate-desktop/libmateweather/).

**Comment by Thomas-N** [comment]
Should I repost the issue on libmateweather's issue tracker?

**Comment by monsta** [comment]
Yes, and this one can be closed (github doesn't allow moving bug reports between projects).
