### ISSUE TITLE
'Workspace Switcher Preferences' help for workspace name change

### ISSUE THREAD

**Issue by rebelxt** [mate-desktop/mate-applets#204]
The workspace names in the 'Workspace Switcher Preferences' dialog can be changed. However, there is no indication anywhere in the help guide that this is possible. Also, the method required to effect name changes is not intuitive. I would suggest that something like the following paragraph be added to the 'Workspaces' page in the 'Desktop User Guide' (gosoverview.xml):

`<para>The default workspace names can be changed to something more to your liking. Open the "Workspace Switcher Preferences" dialog. Click on the name to be changed; the entire line is highlighted. Click on the name a second time; only the name will be highlighted. This is not a double-click; there must be a short delay between  between clicks. Alternatively, press the Enter key instead of the second click. Type the new name and press the Enter key. Repeat for each name to be changed. Click the Close button when these and any other changes have been made.</para>`

There is no explicit page describing all the options for the 'Workspace Switcher Preferences'. Such a page could instead be added to the user guide. This would replace the 'Adding Workspaces' page in  the user guide.
##

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
