### ISSUE TITLE
window-picker-applet built against GTK3+ doesn't function correctly

### ISSUE THREAD

**Issue by apolitech** [mate-desktop/mate-applets#205]
Not all the open apps will apear but you can try to guess click on the bar to open them
 A minimised application can't be maximised/restored when the Window Picker Applet is in a panel.And you can not restore them with alt-tab .
This bug persists from mate 1.14
Look at the video  https://youtu.be/VVI3574L28U
I am using Ubuntu MATE 16.10 daily with MATE 1.15 latest 
Bug reported on ubuntu mate launchpad https://bugs.launchpad.net/ubuntu-mate/+bug/1608710
##

**Comment by flexiondotorg** [comment]
The is a bug is mate-netbook. After some testing the effect of this bug is that a minimised applications can't be maximised/restored when the Window Picker Applet is in a panel. Not all the running applications are listed in the Window Picker Applet either.

**Comment by flexiondotorg** [comment]
@monta These issues fixed by the following commits, right?

  * https://github.com/mate-desktop/mate-netbook/commit/3c33e5cda7f356f47dffc717a900591820ef207c
  * https://github.com/mate-desktop/mate-netbook/commit/b0dba632e2c1da952661ec67d1ca7821fa40ac7b

**Comment by monsta** [comment]
Should be fixed by now.
If not, please open a new issue in https://github.com/mate-desktop/mate-netbook/ - window picker applet is there, not here.
