### ISSUE TITLE
Clock doesn't respect LC_TIME

### ISSUE THREAD

**Issue by Mikaela** [mate-desktop/mate-applets#214]
I ran `sudo localectl set-locale LANG=en_GB.UTF-8 LC_TIME=en_DK.UTF-8 LC_MONETARY=fi_FI.UTF-8 LC_NAME=fi_FI.UTF-8 LC_TELEPHONE=fi_FI.UTF-8` with the locales generated and rebooted and I exptected MATE would start showing the date in ISO 8601 which en_DK.UTF-8 uses.

However I continued seeing `Sun 16 Oct, 21:17:06` instead of something what I see in LC_TIME supporting application (Claws Mail), `Sunday 2016-10-16 21:17:06`.
- https://wiki.archlinux.org/index.php/locale#LC_TIME:_date_and_time_format
##

**Comment by monsta** [comment]
The clock is in mate-panel, please open a new report in mate-panel repo if you still have the problem.
