### ISSUE TITLE
FIX Workspace Switcher: increase the height of workspace list or allow resizing the window

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/mate-applets#215]
currently the window only fits 2 workspaces and it is not possible to resize it

increase the list height or make it have automatic height based on the amount of workspaces. so it would start scrolling when its reaching the height of the screen

![screenshot at 2016-11-12 07 53 34](https://cloud.githubusercontent.com/assets/740826/20236009/6a094a86-a8ad-11e6-90be-ddb254ea070e.png)

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
