### ISSUE TITLE
ADD Workspace Switcher: ability to sort workspace order in list

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/mate-applets#216]
the keyboard shortcuts should still be bound to the sort order nr, but I want to resort my workspaces every few weeks (so that the contents of the workspace moves too, so just changing the label is not enough)

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.

**Comment by ArsenShnurkov** [comment]
So, the "workspace-switcher" applet still doesn't have the ability to set/change order for workplaces in 2021...

**Comment by allanlaal** [comment]
please vote here: https://github.com/mate-desktop/mate-panel/issues/688

**Comment by allanlaal** [comment]
@ArsenShnurkov  and others:

vote on: 

sorting would happen by dragging the workspace icon around in the panel applet

**Comment by EinstokFair** [comment]
Dragging is already used to move applications between workplaces
