### ISSUE TITLE
Revive Window Applets for Mate

### ISSUE THREAD

**Issue by elypter** [mate-desktop/mate-applets#218]
Gnome developers are working on "Window Applets" right now which was an applet that allows you to show the window title and min/max/close buttons on the panel. This allows to save vertical screen space just like ubuntu netbook remix did. It has been abandoned but was recently revived:

https://bugzilla.gnome.org/show_bug.cgi?id=770795

there was also a version for mate but it is no longer working. It would be cool if this could become part of the official mate applets too.

**Comment by mrnhmath** [comment]
So now we have GNOME-Flashback window-applets and IKRadulov's window-applets. I've only tested the former and it looked pretty good, which one shall we base on?

**Comment by flexiondotorg** [comment]
I've been communicating with @IKRadulov and his version is now packaged for Debian and Ubuntu.

**Comment by IKRadulov** [comment]
I would recommend using the original version as a base since my lacks translations and since I don't understand how they sync with WM themes I made my version with Gtk.IconTheme().

**Comment by monsta** [comment]
So it's implemented in 3rd party applet(s).
