### ISSUE TITLE
mate-volume-control-applet crashing - no volume control icon on panel

### ISSUE THREAD

**Issue by adf20** [mate-desktop/mate-applets#222]
Hello, after about an hour or two volume control icon disappear from panel,
because mate-volume-control-applet crashing and when i run it from terminal, again working few hours and then crash, report from terminal below:

-----------------------------------------------------------------------------
????????:~$ mate-volume-control-applet                   
(mate-volume-control-applet:20667): Gtk-WARNING **: Calling gtk_widget_realize() on a widget that isn't inside a toplevel window is not going to work very well. Widgets must be inside a toplevel container before realizing them.

(mate-volume-control-applet:20667): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(mate-volume-control-applet:20667): Gdk-CRITICAL **: gdk_window_get_scale_factor: assertion 'GDK_IS_WINDOW (window)' failed
**
Gtk:ERROR:/build/gtk+3.0-9JqLNv/gtk+3.0-3.22.5/./gtk/gtkwidget.c:5808:gtk_widget_get_frame_clock: assertion failed: (window != NULL)
--------------------------------------------------------------------------------

????????:~$ mate-volume-control-applet --version
mate-volume-control-applet 1.16.0

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-media/issues/89
