### ISSUE TITLE
WIndow List Applet. Left click followed by right click will give height-reduced popup window

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-applets#223]
System: Fedora 25 (64bit)  Mate 1.16.1
If I have grouped windows and at some point do a left click and later a right click (to maybe close the window from the popup menu), the popup will look very odd.

Normal Left click.
![a](https://cloud.githubusercontent.com/assets/3275361/22205130/bd5354b0-e175-11e6-8c51-ce840f40139d.png)

Right click after left click:
![b](https://cloud.githubusercontent.com/assets/3275361/22205139/c4c7aafc-e175-11e6-9e53-21c051e947ac.png)

If i right click without having left clicked before, I get the expected size behavior in the popup:
![c](https://cloud.githubusercontent.com/assets/3275361/22205156/d23d0100-e175-11e6-8113-4b46d5547f4c.png)

**Comment by monsta** [comment]
This applet is a part of [mate-panel](https://github.com/mate-desktop/mate-panel). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
