### ISSUE TITLE
mate-desktop-button

### ISSUE THREAD

**Issue by erikdubois** [mate-desktop/mate-applets#228]
I hope I am reporting this on the right github. When making the panel transparent it is obvious something is wrong with the applet or icon of mate-desktop-button. An image will clarify the issue.
![report](https://cloud.githubusercontent.com/assets/10594806/22741152/7ac6fd50-ee12-11e6-8721-695781f9780a.png)

**Comment by monsta** [comment]
This applet (show-desktop) is actually from mate-panel package. But it's probably a theme issue. Can you check it with Menta/Bluementa and Blue/Green-Submarine themes?

**Comment by raveit65** [comment]
Is this Mate gtk2 ?
Can you give me a favor and post more infos like gtk+ version, does your distro ship Mate with gtk2 or gtk3 support, this and next time if you report a UI issue?
I do not use linuxmint in result your report is a black whole for me ;-)

**Comment by monsta** [comment]
It's GTK+2 build, Mint still has it

**Comment by raveit65** [comment]
OK, with rhel7 or f24 i don't see such funky bogus with our themes.
Of course Traditional, BlackMATE or Greenlaguna writes a background on the GtkButton of the applet.
With Submarine or Menta themes i have full transparency.

**Comment by monsta** [comment]
I guess it should be reported at https://github.com/andreisergiu98/arc-flatabulous-theme
