### ISSUE TITLE
multiload: permission denied on docker filesystems (`nsfs` mountentries)

### ISSUE THREAD

**Issue by Sanva** [mate-desktop/mate-applets#230]
Hi all,

Having `mate-panel` with the multiload applet with disk monitor active, if I run some docker containers, I get the syslog **full** [1] of this kind of messages:

```console
Mar 12 11:52:51 VirtualBox-mentolado org.mate.panel.applet.MultiLoadAppletFactory[18558]: glibtop(c=19503): [WARNING] statvfs '/run/docker/netns/e01a78e99368' failed: Permission denied
```

I've tested it with System Monitor (multiload)

- 1.17.0 panel applet compiled from git `master` with Linux Mint 18.1 (VirtualBox)
- 1.14.1 panel applet included in Linux Mint 18.

This seems related to #171 —specifically, it looks the same as reported by last comment in that issue ( https://github.com/mate-desktop/mate-applets/issues/171#issuecomment-232149180 ) —but the issue may be not the same.

Please note that the applet still works as expected: It shows the disk load correspondent to containers I/O activities —since that is reported in the mountpoint of the real filesystem, providing it is a local one.

[1] The number of records per second looks like *monitor update interval* × *number of docker containers running*.

**Comment by Sanva** [comment]
I've been looking into it and here [1] you can find a really simple —in
terms of code change— fix. It looks like the offenders are
the `nsfs` *mountentries*, type that seems to correspond
to Linux Namespace Filesystem [2] [3] .

I've tested that change and it is true that ignoring those type of
filesystem still allows the panel to show the disk activity correspondent
to I/O from docker containers.

My doubt is... may this have problems with `nsfs` *mountentries* not from
docker? I suposse that the real question here is, **does it make sense to try
to measure `nsfs`?** That's why I still haven't made any pull request.
(May this [4] be related? —sorry, I've found little information about
this *NSFS filesystem* thing, and it is too low level for me...)

By the way, I think it would be of value to have some comment in the code
about why types `smbfs`, `nfs` and `cifs` are currently being ignored.

Any clues on this?

[1] https://github.com/Sanva/mate-applets/commit/cc5f73d418a9bd4f01bcae04508fc6d115bfeae6
[2] https://github.com/torvalds/linux/commit/e149ed2b805fefdccf7ccdfc19eca22fdd4514ac
[3] https://lwn.net/Articles/699819/ (search *nsfs*)
[4] https://patchwork.kernel.org/patch/6803321/

**Comment by rabin-io** [comment]
Have the same problem, https://bugzilla.redhat.com/show_bug.cgi?id=1355867

**Comment by raveit65** [comment]
I was able to reproduce the problem with using a docker-storage in fedora 26.
For others here is a very good HowTo for using a docker-image with a docker-storage (usb-stick) in fedora by @rabin-io .
https://bugzilla.redhat.com/show_bug.cgi?id=1355867#c18
The result was those messages in journal log
```
Nov 21 16:30:54 mother.mother.loc org.mate.panel.applet.MultiLoadAppletFactory[1514]: glibtop(c=1907): [WARNING] statvfs '/var/lib/docker/devicemapper/mnt/2799eb279404a7a5f3496b6f5b0ce2bc46b88d834663b1' failed: Keine Berechtigung
Nov 21 16:30:55 mother.mother.loc org.mate.panel.applet.MultiLoadAppletFactory[1514]: glibtop(c=1907): [WARNING] statvfs '/var/lib/docker/devicemapper/mnt/2799eb279404a7a5f3496b6f5b0ce2bc46b88d834663b1' failed: Permission denied
```
@ marosg42
Can you please take a look at it?

**Comment by Mibou** [comment]
Able to reproduce with docker in Debian Buster.

**Comment by uvwild** [comment]
also in ubuntu16.04

**Comment by science695** [comment]
also in ubuntu 17.10

**Comment by dmitry** [comment]
More details on similar issue: https://bugzilla.redhat.com/show_bug.cgi?id=1355867

**Comment by uvwild** [comment]
is this fix gonna make it to any release?
I cant use the journals anymore with 2 entries per second on 16.04

**Comment by dseomn** [comment]
I'm seeing similar error messages with a `bind` mount. (Should I file a separate bug?)

Log message example:

```
Jan 21 00:03:16 solaria org.mate.panel.applet.MultiLoadAppletFactory[1141]: glibtop(c=21545): [WARNING] statvfs '/srv/slow-disk/home/dseomn/Music/master' failed: Permission denied
```

Relevant parts of `/etc/fstab`:

```
[redacted] /srv/slow-disk ext4    defaults        0       2
/srv/slow-disk/home/dseomn/Music /home/dseomn/Music none bind 0 0
/home/dseomn/Music/master.rw /home/dseomn/Music/master none bind,ro 0 0
```

**Comment by lukefromdc** [comment]
I have  /home/games  bind mounted on   /usr/share/games to keep that rather large directory out of routine filesystem backup handling. On adding the multiload applet to a panel and turning everything on I did not get any warnings from the applet in a terminal from which I ran 
`mate-panel --replace`
nor in syslog.
I am running on bare metal if that makes any difference

**Comment by dseomn** [comment]
I'm betting the `ro` option and/or the bind-within-bind is part of what's triggering the issue, since I have other bind mounts that aren't showing up in syslog

**Comment by Sanva** [comment]
Hi!

You may find interesting that this bug was already present and is already solved in `gnome-applets` → https://gitlab.gnome.org/GNOME/gnome-applets/issues/1 .

**Comment by raveit65** [comment]
Ok, this is the PR for the report https://gitlab.gnome.org/GNOME/gnome-applets/merge_requests/1

**Comment by raveit65** [comment]
> did you remember to enable the harddisk monitoring in the applet ?

@rabin-io 
No, i am answering on too much reports here or at rhbz. And i forgot configs which i don't need for myself very fast :P
I just followed your instructions but i didn't get the warnings with/without to PR.
I can build a rpm for your your (which?) fedora version.

**Comment by rabin-io** [comment]
F29 x64

**Comment by rabin-io** [comment]
I can confirm that using the above package, seems to resolve the problem. I don't see any messages on journald. :+1:  

thanks @raveit65 :)

**Comment by raveit65** [comment]
Ok, i could reproduce the issue again today.
Usb-stick was to  small :)
```
[root@mother rave]# /usr/bin/container-storage-setup
INFO: Volume group backing root filesystem could not be determined
ERROR: There is not enough free space in volume group vg_docker to create data volume of size MIN_DATA_SIZE=2G.
```
Adding MIN_DATA_SIZE=1G to /etc/sysconfig/docker-storage-setup helps a lot.
And the PR fixes the problem :)

**Comment by yetist** [comment]
Today I got this similar output in mate-system-monitor:
```
$ LC_ALL=C mate-system-monitor
glibtop(c=17194): [WARNING] statvfs '/run/docker/netns/3ca4bf92f6e8' failed: Permission denied
glibtop(c=17194): [WARNING] statvfs '/run/docker/netns/3ca4bf92f6e8' failed: Permission denied
```

After checking libgtop, I think this is the upstream bug of libgtop. 
In the source directory of libgtop, after running `./examples/df`, I get the following output:
```
$ ./examples/df |grep statvfs
glibtop(c=6191): [WARNING] statvfs '/var/lib/docker/overlay2/805a7181fc7ce1b3f26d4610e2b9c11738b9c67f31e2ae2d75ee7e' failed: Permission denied
glibtop(c=6191): [WARNING] statvfs '/var/lib/docker/containers/a1fca29d198ad64e5048a08a1320c9e5945c96dbbc1dd49a88c3' failed: Permission denied
glibtop(c=6191): [WARNING] statvfs '/run/docker/netns/3ca4bf92f6e8' failed: Permission denied
$ sudo ./examples/df |grep statvfs
glibtop(c=6208): [WARNING] statvfs '/var/lib/docker/overlay2/805a7181fc7ce1b3f26d4610e2b9c11738b9c67f31e2ae2d75ee7e' failed: No such file or directory
glibtop(c=6208): [WARNING] statvfs '/var/lib/docker/containers/a1fca29d198ad64e5048a08a1320c9e5945c96dbbc1dd49a88c3' failed: No such file or directory
```
So, the bug should be reported upstream.

**Comment by science695** [comment]
Thanks @yetist for reporting it upstream: https://gitlab.gnome.org/GNOME/libgtop/issues/42
