### ISSUE TITLE
Notification Area 1.18 - double network conections

### ISSUE THREAD

**Issue by philthynz** [mate-desktop/mate-applets#237]
Ubuntu 16.04
Mate Desktop 1.18 from ppa https://launchpad.net/~jonathonf/+archive/ubuntu/mate-1.18

Notification Area 1.18 shows 2x network connections:

![image](https://cloud.githubusercontent.com/assets/17504095/24269376/4aa7d916-1011-11e7-892a-ccaff93f243e.png)

Removing the applet makes it disappear for a few minutes, but it soon comes back

Any one else having same issue?

**Comment by raveit65** [comment]
Why reporting here?
Use launchpad please.

**Comment by monsta** [comment]
Yes, this one belongs to Launchpad. I confirm the issue, and some people also noticed it in Ubuntu 17.04, but it's not about mate-applets for sure. Either it's something in network manager applet, or something in our new status-notifier support in the notification area. I'll try to find it out later.

**Comment by monsta** [comment]
Turned out to be related to SNI support in mate-panel after all (https://github.com/mate-desktop/mate-panel/issues/539). Fixed in https://github.com/mate-desktop/mate-panel/commit/2f5fb93bb06fd13e60d18b7b0bfcf0a0b13f2a47. We'll make a new 1.18.x release later.
