### ISSUE TITLE
Window selector now scrolls wildly

### ISSUE THREAD

**Issue by egrosclaude** [mate-desktop/mate-applets#243]
I just updated LMDE2 MATE and I'm overly disappointed with my new window selector. I was used to having a list of windows to choose from, now I have a single line with up and down arrows --This is useless to me, is there any way to get the former behavior back?

**Comment by raveit65** [comment]
I can't confirmed with 1.18 and a theme from Mate upstream (Blue Submarine).
![bildschirmfoto zu 2017-05-08 07-51-53](https://cloud.githubusercontent.com/assets/961604/25791869/81fae018-33c3-11e7-975c-e2877a475860.png)
I suggest to file out a report against linuxmint,

**Comment by egrosclaude** [comment]
Thank you, @raveit65, my bad. Please dismiss and close.

**Comment by monsta** [comment]
LMDE issues thread: https://forums.linuxmint.com/viewtopic.php?f=236&t=244807
