### ISSUE TITLE
invest [improvement]: export/import & manual editing

### ISSUE THREAD

**Issue by DJCrashdummy** [mate-desktop/mate-applets#246]
lets assume i've got a kind of a watchlist and want to discuss it from time to time with friends or i manage a little portfolio for my family.

- so it would be very nice to export the list of stocks, send it to them and they can easily import it and watch the development without further actions.
- to spin this idea a little bit further an option before/while exporting to skip the personal information like amount, price, etc. would be perfect.
- and just to mention it: an automatic exchange or better a real synchronization (one-way/two-way/read-only) via FTP (maybe in conjunction with mintupload) or WebDAV would be the icing on the cake.

_PS: i know as a workaround the files are stored in `~/.config/mate/invest-applet/` and can be copy&pasted, but for not so techie people this is a bit troublesome. not to mention that the necessary restart/relogin after every "import" is really tedious._
- **to overcome the restart/relogin after manually editing/pasting the files (maybe reload the `*.pickle`-files for every update) would be a huge relief.**

by the way: is there somewhere a little bit of a documentation about how the information is stored? - unfortunately i didn't find anything at mate-desktop.org or wiki.mate-desktop.org and just figured out myself, that the `quotes.csv` isn't necessary but the structure of `stocks.pickle` and `config.pickle` seems a little bit of a mess to me...

_PPS: i know for a real portfolio the invest-applet is useless because of the lacking history, but i don't think this should prevent other improvements like the watchlist-exchanging._

**Comment by monsta** [comment]
The applet is removed now, see #297 and #303.

**Comment by lukefromdc** [comment]
Note that the reason this applet was removed was Yahoo's decision to discontinue the API used for the applet and the lack of any suitable free replacement.
