### ISSUE TITLE
invest [enhancement]: different groups and/or lists

### ISSUE THREAD

**Issue by DJCrashdummy** [mate-desktop/mate-applets#247]
i can imagine the ability to create more than one list and to switch between them (e.g. one for the portfolio and one for the watchlist or simply for different portfolios) would be a nice feature.

also "just" the ability to create groups in one list can be useful (e.g. for different asset classes) but this would interfere a little bit with the very nice sorting (just sort in groups or overall?)... and so i guess different lists may be easier to implement.

**Comment by monsta** [comment]
This applet no longer works at all due to Yahoo's actions, so we'll probably drop it. See https://github.com/mate-desktop/mate-applets/issues/297. If you know someone who is willing to take over the maintaining, please tell us there.

**Comment by monsta** [comment]
The applet is removed now.
