### ISSUE TITLE
StickyNotes: notes are not saved and lost silently on logout

### ISSUE THREAD

**Issue by oliver-joos** [mate-desktop/mate-applets#254]
#### Expected behaviour
User-entered text should be saved to a file, normally in ~/.config/mate/stickynotes-applet.xml

#### Actual behaviour
StickyNotes fails to save its data if directory ~/.config/mate/ does not exist. Unfortunately in wide-spread distros like Ubuntu 16.10 MATE and Linux Mint 18.x MATE there is no directory mate/ in ~/.config/
There is no feedback to the user about the problem. Only in /var/log/syslog there are errors:
`org.mate.panel.applet.StickyNotesAppletFactory[1788]: I/O error : No such file or directory`

#### Steps to reproduce the behaviour
1. Boot a Live-DVD or fresh install of Ubuntu MATE or Linux Mint MATE
2. Add the StickyNotes applet to the panel
3. Create a new note by double-clicking the StickyNotes icon
4. Enter some text
5. Logout and login again - your text is lost

#### MATE general version
MATE 1.18.1

#### Package version
Affected versions are: mate-applets 1.14.0, 1.16.0 and 1.18.1. On my up-to-date Linux Mint 18.2 its 1.18.1-1+sonya

#### Linux Distribution
I checked and saw that Ubuntu 16.10, Linux Mint 18.0, 18.1 and 18.2 are affected.

**Comment by raveit65** [comment]
I can confirm that with a new fresh unreleased fedora 26 installation the directory ~/.config/mate/ is missing.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-applets/commit/d7b09bc1837535cfb9baba669410f721957d984f

**Comment by monsta** [comment]
Fix is released in version 1.18.2.

**Comment by filippossemere** [comment]
> Fix is released in version 1.18.2.

I had two locked notes go missing today, without any error messages. Is it possible to recover?

**Comment by oliver-joos** [comment]
All notes are stored in one file. In a MATE desktop this is **~/.config/mate/stickynotes-applet.xml**
If you have a backup of this file then you can:

1. Remove SickyNotes  applet from panel
2. Restore stickynotes-applet.xml
3. Add SickyNotes applet again

Please note that StickyNotes uses a risky storage algorithm. Together with dangerous filesystem options (like ext4 "nobarrier") or dangerous device cache options data loss may happen!
