### ISSUE TITLE
Mate Volume Control Applet - Arrow Keys Don't Work

### ISSUE THREAD

**Issue by karakartala** [mate-desktop/mate-applets#256]
#### Expected behaviour
I have updated my LinuxMint from 18.1 to 18.2. Formerly, if I click volume control applet, i can control the volume level trough up/down keys.

#### Actual behaviour
But now, they don't work. Arrow keys can't control the volume level.

#### MATE general version
MATE 1.18.0

#### Linux Distribution
Linux Mint 18.2

**Comment by lukefromdc** [comment]
First things first: The volume control applet is from mate-media, not mate-applets. Please open a new report there and close this one..

I just tested this, it looks like the arrow keys don't follow the mouse focus to the volume applet even if you have the volume slider open and under the cursor. Even clicking on it won't change this. leaving the arrow keys controlling the last window that had focus prior to mousing to the volume slider.

The volume-up and volume-down keys work fine, but not all keyboards have those. Probably their function could be transferred to arrow keys in setting shortcuts, but probably that would then be all they did.

**Comment by karakartala** [comment]
In the past, no matter mouse location or background windows etc., when I clicked volume applet, arrow keys(up/down) control the volume level. I don't think the problem is about shortcut settings. Volume-up and volume-down keys were working. And they are still working fine.
Thank you for reply.
