### ISSUE TITLE
Stickynotes requested but dependency not found

### ISSUE THREAD

**Issue by shevegen** [mate-desktop/mate-applets#270]
While trying to compile mate-applets 1.19.0, I get:

"checking for STICKYNOTES... no
configure: error: Stickynotes explicitely requested but dependency not found"

Could the configure script be more specific and tell me which dependency it is
needing?

**Comment by shevegen** [comment]
Hmm ... did someone or something edit my above post? That was ... very distracting, some bounty bot or something ... may be better if it would not edit the content I wrote but instead post below ... :\

**Comment by marosg42** [comment]
Do you have gtksourceview-3.0 installed?
Also, you should see some output about what is missing when you run autogen.sh
