### ISSUE TITLE
Cpufreq applet frequency label causing units label to jump

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-applets#281]
#### Expected behaviour
Changing width of numbers in frequency label should not cause any other widgets to jump/move

#### Actual behaviour
As the CPU frequency changes (a lot with recent kernels), the changing width of the frequency numbers causes the units label to jump. This can be seen with all themes on close examination but is aggravated by any theme setting bold text on the panel

#### Steps to reproduce the behaviour
Add the cpufreq applet to the panel, change the frequency or watch it change around on any governor not forcing a fixed frequency. Using a theme  (or editing an existing theme) setting a bold font on the panel will make this much easier to see, but it is visible in all themes on close examination

#### MATE general version
1.19 from git master

#### Package version
Locally compiled from 1.19.2+git master as of 10-25-2017 over GTK 3.22.24

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as this is a locally compiled package from a newer version than Debian distributes

**Comment by monsta** [comment]
As #280 is merged, should it be considered fixed?

**Comment by lukefromdc** [comment]
Yes, this is fixed and this report should have been closed then
