### ISSUE TITLE
1.18.2 in pre-release folder

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-applets#282]
@monsta 
Please test and tag/release the package if all is fine.
I am not sure about the tranlation updates.
For the future we need to find a better solution with updating from transifex.
Maybe we connect transifex with stable branch and switch 3 months for next major release to master.

**Comment by monsta** [comment]
Ah, I was going to do it next. Should be ok, but I'll test it one more time.

**Comment by monsta** [comment]
Translations seem to be ok. Nobody updated strings on Transifex after https://github.com/mate-desktop/mate-applets/commit/5fedc5bcdc4f276709552ca40958442151bb97b4 (new GSettings key with translatable description), so it should be ok for 1.18.

**Comment by monsta** [comment]
Ok, tagged and released.
