### ISSUE TITLE
No tooltip for multiload applet

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-applets#286]
#### Expected behaviour
Hovering mouse over multiload applet should display tooltip like the other applets do

#### Actual behaviour
Hovering mouse over multiload applet usually does nothing, I saw the tooltip only once

#### Steps to reproduce the behaviour
Put the multiload applet on a panel (top or bottom, it made no difference in my tests), and hover the mouse over it

#### MATE general version
1.19 from git master as of Nov 9, 2017

#### Package version
Locally compiled against GTK 3.22.25 and glib 2.54.2

#### Linux Distribution
Debian Unstable with locally compiled GTK 3.22.25 and glib 2.54.2

#### Link to downstream report of your Distribution
None as this is locally compiled mate-applets from git

**Comment by marosg42** [comment]
Depending on the load it takes sometimes 7-8 seconds before tooltip is displayed. However it looks like GTK issue because applet calls gtk_widget_set_tooltip_text() correctly, immediately after mouse hovers over applet.
@lukefromdc, could you check if tooltip appears later? Just let mouse hover for 10 seconds.

**Comment by lukefromdc** [comment]
OK, I can confirm that: after about 10 seconds here the tooltip usually appears. Sometimes it does not, wonder if that's a cursor position issue within the applet (or withing X etc). This is on testing with the CPU at idle.

**Comment by mbkma** [comment]
@lukefromdc can you still reproduce this issue? I found that with 1.26 the tooltip comes up fine.

**Comment by lukefromdc** [comment]
No longer have this problem with 1.26 here either, closing
