### ISSUE TITLE
Global menu mate applet

### ISSUE THREAD

**Issue by Ygarr** [mate-desktop/mate-applets#287]
AKA topmenu
#### Expected behaviour
Maximize window,  getting window menu on mate-panel. Distro independent package

#### Actual behaviour
empty, absent

#### MATE general version
1.18, 1.19

#### Package version
no data

#### Linux Distribution
Seems all except Ubuntu-like.: mageia(rpm), debian, antergos(arch),sabayon(gentoo) 

#### Link to downstream report of your Distribution
Related but old links:
https://git.javispedro.com/cgit/topmenu-gtk.git/about/
https://aur.archlinux.org/packages/topmenu-gtk-git/
http://www.webupd8.org/2014/12/get-global-menu-in-mate-18-with-topmenu.html

**Comment by flexiondotorg** [comment]
TopMenu has been abandoned by upstream. If you're interested in Global Menus then I recommend https://github.com/rilian-la-te/vala-panel-appmenu
