### ISSUE TITLE
Mate Dock Applet can't display or scroll more apps than the display allows

### ISSUE THREAD

**Issue by BikyAlex** [mate-desktop/mate-applets#288]
#### Expected behaviour
Auto scroll when reaching top or bottom of the panel

#### Actual behaviour
Nothing happens, can't scroll through apps

#### Steps to reproduce the behaviour
Select Mutiny Layout
Fill the Mate Dock Applet with apps (pinned opened, pinned closed, unpinned open, doesn't matter)
Try scrolling through apps

#### MATE general version
1.18.0

#### Linux Distribution
Ubuntu Mate 17.10

![mateproblems](https://user-images.githubusercontent.com/17931169/33004343-df0feb8c-cdc8-11e7-98aa-0d80d47a9c52.jpg)
The first picture shows a random app (in this case Welcome app) opened and barely visible on the dock, while the Trash bin and Brisk Menu are completely hidden, with no option to scrolling to them

![mateproblems2](https://user-images.githubusercontent.com/17931169/33004344-df2faf80-cdc8-11e7-839f-ad7cfeeada6c.jpg)
The second picture shows how Dock Applet is supposed to look when Welcome app was closed and one app was unpinned from the dock, in order to make all apps visible.

**Comment by flexiondotorg** [comment]
Please file this bug with the mate-dock-applet project 😀 https://github.com/robint99/mate-dock-applet

**Comment by BikyAlex** [comment]
Yes, sorry, I already checked this after raveit65 mentioned it. I'm sorry for filling it in the wrong place (having "Mate" in the name makes it sound pretty official and I got confused) - there are already 2 bug reports with the same bug I had, I don't think it's worth creating another one...
https://github.com/robint99/mate-dock-applet/issues/108
https://github.com/robint99/mate-dock-applet/issues/110

**Comment by flexiondotorg** [comment]
Thanks @BikyAlex
