### ISSUE TITLE
[gtk2] clock and weather applet don't show up

### ISSUE THREAD

**Issue by kuzetsa** [mate-desktop/mate-applets#292]
#### Expected behaviour

normal functionality for clock and weather applet

#### Actual behaviour

missing applets (clock / weather)

#### Steps to reproduce the behaviour

building / configuring for gtk2

#### MATE general version

1.16

#### Package version

1.16.0

#### Linux Distribution

gentoo

#### Link to downstream report of your Distribution

https://bugs.gentoo.org/633772

**Comment by monsta** [comment]
> I noticed the default clock applet does not show up in the panel. Adding it manually does not make it appear either. Same holds true for the weather applet. All the other applets can be added and work.

Please check your build settings, in particular, check that libmateweather is actually built with the same GTK+ as mate-panel and mate-applets.
