### ISSUE TITLE
wifi connection dialogue "save password" checkbox feature

### ISSUE THREAD

**Issue by shalnoff** [mate-desktop/mate-applets#296]
#### Expected behavior

would be great to have additional checkbox "save password" in  "password" dialogue. That would prevent system from saving of sporadic/"single use" connections and, additionally, in some level increase security by making system avoid accidental connections to this AP in the future. 

#### Actual behavior
no such option in the connection dialogue

#### Steps to reproduce the behavior

select new AP from the list by pressing right mouse button on applet icon in the panel. 
The following "password" dialogue has no such future. 

#### Linux Distribution

All versions

**Comment by monsta** [comment]
Network Manager applet is not a part of MATE desktop.
