### ISSUE TITLE
Invest Applet no longer working

### ISSUE THREAD

**Issue by mr-mop** [mate-desktop/mate-applets#297]
#### Expected behaviour
Invest applet downloads stock quotes

#### Actual behaviour
Invest applet only downloads the following:
"It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com."

#### Steps to reproduce the behaviour
Add some stock symbols to the applet and attempt to refresh

It appears the API that was used has been discontinued.
https://yahoo.uservoice.com/forums/382977-finance/suggestions/32103877-yahoo-stock-quote-api-please-bring-back

#### MATE general version
MATE Desktop Environment 1.8.1

#### Package version
mate-applets (1.8.1+dfsg1-3)

#### Linux Distribution
Debian Jessie

**Comment by monsta** [comment]
If they killed the API, how are we supposed to "fix" it?

**Comment by flexiondotorg** [comment]
Unless there is a drop in replacement API, which reading the thread at Yahoo it seems there will never be, I suggest we drop this applet.

**Comment by monsta** [comment]
I agree. If there's no similar API on any other website, this applet will be simply useless.

**Comment by mr-mop** [comment]
Any use? https://www.alphavantage.co/

**Comment by monsta** [comment]
@flexiondotorg: their "free API key" seems suspicious. Are you familiar with any services which offer API on such terms?

**Comment by lukefromdc** [comment]
I get "No stock quotes are currently available" and this began very recently. 

We need to be very careful about online services that may offer "free" service but be interested in collecting personal information, such as logging all places a unique computer connects from. Fortunately, an applet like this should leak a lot less data than a browser. 

Still, we may want to drop the applet unless we can find another reputable service to connect it to.

**Comment by monsta** [comment]
I'm inclined to drop it (or pass it to someone) also because it's quite specific applet, unlike other ones in the package. I think it's better if it's maintained by someone who knows the problem domain.

**Comment by alexarnaud** [comment]
Le 11/01/2018 à 15:27, monsta a écrit :
> I'm inclined to drop it (or pass it to someone) also because it's quite 
> specific applet, unlike other ones in the package. I think it's better 
> if it's maintained by someone who knows the problem domain.

I agree with you.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by flexiondotorg** [comment]
I agree with dropping this applet, mostly because their is no drop in reputable API replacement. We can revisit this in the future perhaps.

**Comment by lukefromdc** [comment]
I also agree

**Comment by monsta** [comment]
So it's going away: https://github.com/mate-desktop/mate-applets/pull/303

@flexiondotorg: should we make an announcement about this?

**Comment by flexiondotorg** [comment]
I'll post something on the blog. Do we release an updated mate-applets for 1.18 with it removed?

**Comment by monsta** [comment]
It makes sense to drop it in each supported release, though it seems that the deleted applet still stays in the panel if it was there before the upgrade. I have no idea how to fix it, because the applet can have any identifier on the panel, like object-1, object-2, etc.

**Comment by monsta** [comment]
@flexiondotorg: also looks like there's a problem with making a distro patch out of https://github.com/mate-desktop/mate-applets/commit/41f7b7a2a38ca9f3929fcbd88d228b3815034876 - @raveit65 got this today:

```
<raveit65> hmm i need to release a new mate-applets release
<raveit65> Patch #7 (mate-applets_0001-drop-broken-invest-applet-and-all-Python-dependencie.patch):
<raveit65> + /usr/bin/patch --no-backup-if-mismatch -p1 -b --suffix .0001 --fuzz=0
<raveit65> patching file Makefile.am
<raveit65> patching file configure.ac
<raveit65> patching file invest-applet/Makefile.am
<raveit65> patching file invest-applet/data/Invest_Applet.xml
<raveit65> patching file invest-applet/data/Makefile.am
<raveit65> patching file invest-applet/data/art/Makefile.am
<raveit65> File invest-applet/data/art/invest-16_neutral.png: git binary diffs are not supported.
<raveit65> File invest-applet/data/art/invest-22_down.png: git binary diffs are not supported.
<raveit65> File invest-applet/data/art/invest-22_neutral.png: git binary diffs are not supported.
<raveit65> File invest-applet/data/art/invest-22_up.png: git binary diffs are not supported.
<raveit65> no chance to use it as patch
```

**Comment by alexarnaud** [comment]
Le 14/01/2018 à 19:18, monsta a écrit :
> It makes sense to drop it in each supported release, though it seems 
> that the deleted applet still stays in the panel if it was there before 
> the upgrade. I have no idea how to fix it, because the applet can have 
> any identifier on the panel, like object-1, object-2, etc.

If an applet is missing an alert message will be shown and the user has 
to click on drop.

The name of the applet is not important because we can find the 
object-type and the applet-iid to determine if it's the invest applet.

We can imagine to add a condition before to send the popup to the user. 
If the applet-iid is the invest applet we drop it and we could inform 
the user via a pop-up.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by monsta** [comment]
Hmm, it works. How did I miss it?

The only problem is that settings for "objects" themselves are not deleted from dconf, but that's an existing problem which can be also reproduced when installing/adding to panel/uninstalling other applets (e.g. mate-indicator-applet).
