### ISSUE TITLE
Battstat applet memory leak

### ISSUE THREAD

**Issue by n0rad** [mate-desktop/mate-applets#298]
I mostly use suspend on my laptop and reboot only to update the kernel,
`battstat-applet` memory is growing slowly through days till I have to kill it to get back memory.
I'm running since 2d and the applet is using 280Mb of memory.
I will update the issue with memory usage in few days.

#### Steps to reproduce the behaviour
Nothing, just let it run

#### MATE general version
1.18

#### Package version
1.18.2, upower backend enabled.

#### Linux Distribution
archlinux

**Comment by monsta** [comment]
There's an existing report at https://github.com/mate-desktop/mate-applets/issues/225. Please post the updates there.
