### ISSUE TITLE
mate-volume-control-applet crashes when changing device profiles with mate-volume-control

### ISSUE THREAD

**Issue by Asta1986** [mate-desktop/mate-applets#302]
#### Expected behaviour
Using mate-volume-control or pavucontrol hardware device profiles can be switched without effect on the volume applet.

#### Actual behaviour
Sometimes when using mate-volume-control (or pavucontrol) to switch device profiles (in the 'Hardware' tab) mate-volume-control-applet crashes.

#### Steps to reproduce the behaviour
Open mate-volume-control and change device profiles several times.
In my case it occurs with one USB headset and one onboard soundcard, although I'm not sure whether having more than one device has anything to do.

#### MATE general version
1.19.1

#### Package version
mate-applets-1.19.2-2.fc27.x86_64

#### Linux Distribution
Fedora 27.

#### Link to downstream report of your Distribution
-

**Comment by raveit65** [comment]
Sorry, wrong repo.
Can you please file out the report at mate-media?
Sadly, we can't move reports to other repos here at github.
Btw. does abrt gives you a stacktrace?
