### ISSUE TITLE
MicMute does not work in MATE 1.18

### ISSUE THREAD

**Issue by joakim-tjernlund** [mate-desktop/mate-applets#312]
MicMute on my ThinkPad does nothing. Test with KDE mutes the microphone.

**Comment by monsta** [comment]
There are no microphone-related applets in this repo

**Comment by joakim-tjernlund** [comment]
OK, but what repo would it be then? What handles the normal Mute function?

**Comment by monsta** [comment]
Handling media keys like that one is usually done by mate-settings-daemon.

Check https://github.com/mate-desktop/mate-settings-daemon/issues/175, I think it's the same request.

**Comment by joakim-tjernlund** [comment]
ahh, this is the same request, thanks

PS.
I know this is off for this repo/ticket but I don't know of a better way to ask general MATE
questions: Can we have a final MATE 1.18 release ?

**Comment by monsta** [comment]
Final release?

**Comment by joakim-tjernlund** [comment]
Well, perhaps not final but now that 1.20 is out I expect 1.18 releases will be less frequent.
There are fixes in 1.18 branches not yet released and getting those out would be nice

**Comment by monsta** [comment]
Yes, we plan to make more 1.18.x bugfix releases
