### ISSUE TITLE
system monitor applet does not remember width properties just stays at the default 40

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-applets#313]
#### Expected behaviour
The define width is conserved

#### Actual behaviour
The width is restarted

#### Steps to reproduce the behaviour
1) Add the System Monitor applet to the panel
2) Go to the properties of this applet
3) Set the width to 100
4) Restart mate-panel

#### MATE general version
1.20

#### Package version
1.20.0-2

#### Linux Distribution
Debian Sid

#### Link to downstream report of your Distribution
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892106

#### Additional information
It's a regression, in version 1.18 it works correctly. Otherwise, if you look at the stored configuration in gsettings on version 1.18 you will see a "prefs" in the gsettings, it's not the case in 1.20. Prefs seems no longer stored.

Best regards.

**Comment by flexiondotorg** [comment]
Closed via https://github.com/mate-desktop/mate-applets/pull/316
