### ISSUE TITLE
size of multiload applet is not preserved

### ISSUE THREAD

**Issue by marosg42** [mate-desktop/mate-applets#315]
#### Expected behaviour
When OS is rebooted, applet size should be the same as before reboot

#### Actual behaviour
After reboot size is always 40 pixels

#### Steps to reproduce the behaviour
Add system monitor applet to panel, change its size, reboot and see size is bask to 40 pixels. Even without reboot, just going back to preference dialog shows 40 pixels

#### MATE general version
1.20.1, latest git master

#### Linux Distribution
Ubuntu Mate 18.04 beta1

It is a change in gtk/gio/whatever, getting this message

> (mate-multiload-applet:13272): GLib-GIO-CRITICAL **: 16:29:05.588: g_settings_set_value: key 'size' in 'org.mate.panel.applet.multiload' expects type 'i', but a GVariant of type 'u' was given
> Gtk-Message: 16:29:12.758: GtkDialog mapped without a transient parent. This is discouraged.

Previously this type mismatch was ignored, now it prevents to set gsetting

**Comment by marosg42** [comment]
sorry, duplicate of https://github.com/mate-desktop/mate-applets/issues/313

**Comment by raveit65** [comment]
@marosg42 
And why not closing a duplicate to avoid work for other ppl?
