### ISSUE TITLE
Character palette

### ISSUE THREAD

**Issue by apinunt** [mate-desktop/mate-applets#317]
#### Expected behaviour
desired characters be displayed

#### Actual behaviour
characters are displayed on a black background rendering them unreadable

#### Steps to reproduce the behaviour
Add character palette to the panel, select any of the available palettes to be displayed and then select any character from the choices. The background changes to black rendering them unreadable until a system reboot.

#### Link to downstream report of your Distribution ??

Initial display:
![screenshot at 2018-04-22 19-25-53](https://user-images.githubusercontent.com/38540305/39094988-141b9638-4663-11e8-982c-09f46fa39869.png)

After selecting a character:
![screenshot at 2018-04-22 19-24-00](https://user-images.githubusercontent.com/38540305/39094966-c9b63fd0-4662-11e8-9ef2-691ec3155b37.png)

**Comment by lukefromdc** [comment]
Which theme is this in?

**Comment by apinunt** [comment]
Mint-X

**Comment by lukefromdc** [comment]
Can you test this with some of the other themes? This sort of thing is usually theme-specific.

 I do not know how to use the applet, I get a gray background with my UbuntuStudio_Legacy theme(the theme_bg_color) and the character shown on the panel in white. I get an effect looking like a button around each character in the panel can be pressed but then stays pressed if clicked on again.  I do not know if that is intended or not.

**Comment by apinunt** [comment]
Each theme,with the exception of Raleigh performs the same. Only in Raliegh does the background NOT turn black, but we would much prefer to use the Mint-X theme.
/usr/share/themes/Raleigh/gtk-2.0/gtkrc # This theme is the default theme if no other theme is selected.
Some of the themes appear to be gtk2 only and some have a gtk2 and gtk3 folder. I'm assuming any corrective action would have to be made in /usr/share/themes/Mint-X which contains numerous folders for gtk2 and 3, metacity, xfce, etc. We have no idea how to determine where to try and make corrective changes, and assume it would be in one of the files contained in a gtk folder or the metacity.

**Comment by apinunt** [comment]
We've resolved the problem by editing /usr/share/themes/Mint-X/gtk-3.0/apps/mate-applications.css lines 71 and 131 with the following changes:
71	    background-color: #FFFFFF;
131	    background-color: #FFFFFF;
That results in a white background, changing to a light grey when a character is pointed at, remaining grey if selected until unselected by clicking on it again or selecting another character.
We were unable to find a .css file related to Raleigh to compare with the one for Mate-X.
Ideally, we would like to load our theme from our home so that system upgrades will not change our edits.

**Comment by ssrublev** [comment]
I have earlier posted some comments about this overlapping here: https://github.com/mate-desktop/mate-applets/issues/126#issuecomment-305403918

I still sometimes (not always) get this overlapping in various ways in Fedora 28 and Ubuntu 18.04.

**Comment by apinunt** [comment]
Seems to be corrected in Mint 19.
