### ISSUE TITLE
Rebase with gnome-applets

### ISSUE THREAD

**Issue by rcaridade145** [mate-desktop/mate-applets#342]
I've been looking into https://github.com/GNOME/gnome-applets/commits/master  trying to look which changes can be backported.

The only one i've backported into my branch ( https://github.com/rcaridade145/mate-applets/commit/c7b9a5fb528705a5158f0dd91e261ea82fd8a163 )  is https://github.com/GNOME/gnome-applets/commit/f04777973b37265ca9e034421996f16d64853ee2

Seemed easy enough :)

Others i've been looking into are 

https://github.com/GNOME/gnome-applets/commit/daadbbcd3e8a726b0d73fefd476a4c1c4da43a71 
Which seems like it would fix #230 or at least avoid it.

For #225 i couldn't find anything.

My knowledge of the codebase is limited, so my question is on which ones should i focus more, or let's say need more work? @raveit65 @vkareh 

All the best.

**Comment by raveit65** [comment]
Did you test the fix for https://github.com/mate-desktop/mate-applets/issues/230 ?
Feel free to start with a PR for the first one, see my comment in your repo.

**Comment by rcaridade145** [comment]
I'm not very familiar with gtk (still getting to terms with it so please bear with me ) however i've been trying to analyse the code with pvs studio and cppcheck-gui and i noticed this

`57         dot_pixbuf = gtk_icon_theme_load_icon_for_scale (icon_theme, which_dot, icon_size, icon_scale, 0, NULL);
    658 
    659         gdk_pixbuf_composite(dot_pixbuf, mouse_pixbuf, 0, 0, gdk_pixbuf_get_width(dot_pixbuf), gdk_pixbuf_get_height(dot_pixbuf), 0.0, 0.0, 1.0, 1.0, GDK_INTERP_NEAREST, 255);
    660 
    661         surface = gdk_cairo_surface_create_from_pixbuf (mouse_pixbuf, icon_scale, NULL);
    662         g_object_unref(mouse_pixbuf);
    663 
    664         return surface;
    665 }
`
On accessx-status applet.c  .
Should that dot_pixbuf not be also unref?

**Comment by muktupavels** [comment]
Yes, you need unref.

**Comment by rcaridade145** [comment]
@muktupavels @raveit65 Will fix that also then :)

**Comment by rcaridade145** [comment]
@muktupavels @raveit65 Still not very familiar with those pull requests :/ Did a pull request for the stickynotes and then a commit for the issue with accessx-status and then both went to the pull request :|

**Comment by raveit65** [comment]
@rcaridade145 
For accessx-status you need to create a new branch, than a second PR from the new branch won't go in first PR.

**Comment by rcaridade145** [comment]
@raveit65 Ok. I changed the title of the pull request to me more inclusive but if you wish i'll do that later..

**Comment by rcaridade145** [comment]
@raveit65 Thank for taking your time explaining these things  :+1:

**Comment by rcaridade145** [comment]
@raveit65 Done :)

**Comment by rcaridade145** [comment]
This can be closed. Almost 1.5 years old .
