### ISSUE TITLE
battstat manual: external URL points to non-existent page

### ISSUE THREAD

**Issue by rbuj** [mate-desktop/mate-applets#352]
https://github.com/mate-desktop/mate-applets/blob/ec3d9f046e4d5a5caa2960833806545742cae364/battstat/docs/C/index.docbook#L276

**Comment by raveit65** [comment]
We dropped the mailing list a while ago, as most people from team didn't want or hadn't the time to answer there. 
Current point of contact is irc channel mate-dev at freenode.
But sadly i noticed that most team members aren't active there any more or they ignore pings.
So i don't know a solution for replacing the mailing list link.
Let see if other team members will answer here.
Thoughts?
@flexiondotorg 
@clefebvre 
@monsta 
@vkareh 
@lukefromdc

**Comment by raveit65** [comment]
i forgot @sc0w   :)

**Comment by sc0w** [comment]
link to https://github.com/mate-desktop/mate-applets/issues instead?

**Comment by raveit65** [comment]
OK, this part in guide is for bug-reporting and not a general point of contact.
Than replacing the mailing-list link with github (issues) link should be fine.

**Comment by monsta** [comment]
It should be reworded then... the section is called "Getting Help", and I'm sure we wouldn't want people filing bug reports only to seek help instead of reporting some actual bug.

There's nothing else in that section though, so maybe just remove it? Do we have such sections (about getting help elsewhere) in any other manuals?

**Comment by rbuj** [comment]
$ grep --include=\*.{xml,docbook,page} -Rin &quot;http://ml.mate-desktop.org&quot; ./
./mate-user-guide/mate-user-guide/C/gostools.xml:1049:      the mailing list, &lt;ulink type=&quot;http&quot; url=&quot;http://ml.mate-desktop.org/listinfo/mate-dev&quot;&gt;&lt;/ulink&gt;.&lt;/para&gt;
./mate-user-guide/mate-user-guide/C/gosfeedback.xml:72:	url=&quot;http://ml.mate-desktop.org/listinfo&quot;&gt;MATE
./mate-applets/battstat/docs/C/index.docbook:276:        &lt;ulink url=&quot;http://ml.mate-desktop.org/listinfo/&quot;&gt;MATE mailing

$ grep --include=\*.{xml,docbook,page} -Rin &quot;http://live.gnome.org&quot; ./
./pluma/help/C/index.docbook:1365:  		&lt;para&gt;Several plugins come built-in with &lt;application&gt;&amp;app;&lt;/application&gt;, and you can install more. The &lt;ulink type=&quot;http&quot; url=&quot;http://live.gnome.org/Pluma/Plugins&quot;&gt;pluma website&lt;/ulink&gt; lists third-party plugins.&lt;/para&gt;
./pluma/help/C/index.docbook:1410:	&lt;note&gt;&lt;para&gt;For more information on creating plugins, see the &lt;ulink type=&quot;http&quot; url=&quot;http://live.gnome.org/Pluma/Plugins&quot;&gt;&lt;application&gt;&amp;app;&lt;/application&gt; website&lt;/ulink&gt;.&lt;/para&gt;&lt;/note&gt;
./mate-user-guide/mate-user-guide/C/gosfeedback.xml:83:      &lt;para&gt;For more information on joining MATE, please visit &lt;ulink type=&quot;http&quot; url=&quot;http://live.gnome.org/JoinMate&quot;&gt;http://live.gnome.org/JoinMate&lt;/ulink&gt;.&lt;/para&gt;

**Comment by rbuj** [comment]
$yelp help:mate-user-guide/feedback

**Comment by lukefromdc** [comment]
I suggest dropping it, as the mailing list is not used anymore. If we don't have a "helpline" than let's not waste people's time or keep them from defaulting to their usual search engine.

**Comment by raveit65** [comment]
I think dropping the mailing-list link is the best solution because the content of this part isn't about bugreporting.
Current help support are distro forums which support Mate.

**Comment by monsta** [comment]
Ok, so there are only a few places where it's mentioned. Can be safely dropped I guess.

**Comment by tamplan** [comment]
There is the same for http://bugzilla.mate.org/

Do you want i help you to resolve this issue?

If yes, please give me directions or your expectations.
