### ISSUE TITLE
 Applet CPU Frequency Scaling Monitor not working in Ubuntu Mate 18.10

### ISSUE THREAD

**Issue by apolitech** [mate-desktop/mate-applets#363]
#### Expected behaviour
CPU Frequency Scaling Monitor applet to work as intended (to see cpu frequency and to select the power mode)

#### Actual behaviour
CPU Frequency Scaling Monitor will not work (it's not communicating with the cpu and the applet is not visible)

![1](https://user-images.githubusercontent.com/14872517/47254540-789e5900-d46c-11e8-9a00-e25eb349e360.gif)

#### Steps to reproduce the behaviour
Add CPU Frequency Scaling Monitor applet to the bar.

#### MATE general version
1.20.3

#### Package version
mate-applets 1.20.2-2

#### Linux Distribution
Ubuntu Mate 18.10

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/mate-applets/+bug/1798947

**Comment by raveit65** [comment]
Can you control your cpu with cpupower?
example config, see man cpupower.
```
[root@mother rave]# cat /etc/sysconfig/cpupower 
# See 'cpupower help' and cpupower(1) for more info
CPUPOWER_START_OPTS="frequency-set -g performance"
CPUPOWER_STOP_OPTS="frequency-set -g ondemand"
```
 ^^^^^  That will happen when you start the service.
`systemctl enable cpupower.service && systemctl start cpupower.service`

In the end the applet is backend for cpupower.

I didn't notice any problems with the applet here in fedora since years, currently it controls my AMD Ryzen 8/16 core.

**Comment by apolitech** [comment]
i am doing something wrong?
sudo cat /etc/sysconfig/cpupower 
cat: /etc/sysconfig/cpupower: No such file or directory

**Comment by apolitech** [comment]
Failed to enable unit: Unit file cpupower.service does not exist.

**Comment by apolitech** [comment]
so yea ubuntu 18.10 has a problem

**Comment by raveit65** [comment]
cpupower is part of kernel-tools in fedora.
```
[root@mother rave]# dnf provides /etc/sysconfig/cpupower
Last metadata expiration check: 0:12:11 ago on Sat Oct 20 14:05:12 2018.
kernel-tools-4.18.13-200.fc28.x86_64 : Assortment of tools for the Linux kernel
Repo        : @System
Matched from:
Filename    : /etc/sysconfig/cpupower
```

**Comment by selectiveduplicate** [comment]
Under Ubuntu, it's provided as part of the ``linux-tools-common`` package as of [here](https://launchpad.net/ubuntu/bionic/+package/linux-tools-common)- it doesn't seem to be included by default.

**Comment by raveit65** [comment]
Same here in an f28 VM.
I never expect that this works a VM with virtual cores ......
Personal i wouldn't like to see that a VM control my cores on host system ;)

**Comment by raveit65** [comment]
Guys, can you please write it in report if you're using a VM and report hardware issues, next time ?

**Comment by raveit65** [comment]
In qemu-kvm VM:
```
[root@f28-orig rave]# systemctl start cpupower.service 
Job for cpupower.service failed because the control process exited with error code.
See "systemctl status cpupower.service" and "journalctl -xe" for details.
[root@f28-orig rave]# systemctl status cpupower.service
* cpupower.service - Configure CPU power related settings
   Loaded: loaded (/usr/lib/systemd/system/cpupower.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2018-10-20 17:04:08 CEST; 4s ago
  Process: 9366 ExecStart=/usr/bin/cpupower $CPUPOWER_START_OPTS (code=exited, status=237/KEYRING)
 Main PID: 9366 (code=exited, status=237/KEYRING)
```
I assume that controlling cpu freq of a virtual cpu simply isn't supported by linux kernel in a Virtual machine.
Btw. it isn't supported by your virtual software.

**Comment by selectiveduplicate** [comment]
So it works in a native install here on my Ubuntu MATE 18.04.1, but doesn't on a VM running the same distro (UM 18.04.1).

I should mention that I don't have the ``linux-tools-common`` installed on my native/host machine which contains ``cpupower`` within it, but the applet works fine anyway; I installed the package on the VM but that didn't make a difference. 

I am going to investigate with a live USB of UM 18.04 and report back...

**Comment by lukefromdc** [comment]
@selectiveduplicate ,there has been another round of fixes for label rendering in the cpufreq applet, but the last 1.20 release (1.20.2) came out prior to those being cherrypicked to the 1.20 branch. The label cutting should be stopped when 1.20.3 comes out, though you won't see that in an Ubuntu live USB stick until Ubuntu updates their .iso images to a new point release

**Comment by apolitech** [comment]
Again this problem is in 18.10 not in 18.06.x and the os it's installed on my main rig not in a VM

**Comment by raveit65** [comment]
Ok, can you please install linux-tools-common and check if you can control your cpu cores with cpupower?

**Comment by apolitech** [comment]
sudo apt install linux-tools-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-tools-common is already the newest version (4.18.0-10.11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by raveit65** [comment]
sorry, no idea how to install cpupower in ubuntu, i am using only rpm-based distros.
I suggest to ask @flexiondotorg  for help.

**Comment by apolitech** [comment]
$ sudo apt-get install -y linux-tools-$(uname -r)
But still nothing. The same problem.

**Comment by raveit65** [comment]
@apolitech 
Which hardware are you using?
I can reproduce the issue if "AMD Cool and Quiet" option is disable in Bios.
For some reasons this option will be disabled by MSI mobos if you start overclock AMD Ryzen procs.
I never noticed that with a gigabyte board which i used before.

**Comment by apolitech** [comment]
What;))) are you serious. AMD Cool and Quiet is disable :)))) what why why why what

**Comment by lukefromdc** [comment]
@raveit65 reports some MSI motherboards force-disable AMD Cool and Quiet if you overclock. That in my opinion is a blocking concern against buying such a motherboard unless you can get a program working to overclock (and turn OC on and off) from inside Linux

**Comment by apolitech** [comment]
Because we will have more and more rayzen users is there a way to applet to know and tell you something as "as long the x seting is selected this applet won't work"?

**Comment by raveit65** [comment]
Maybe we can write it in documentation?

**Comment by selectiveduplicate** [comment]
I can confirm that this is a hardware issue- the applet works fine with Ubuntu MATE 18.10, as I've just tested it in a live USB ( I have an ASUS mobo).
