### ISSUE TITLE
Glitch in multiload applet

### ISSUE THREAD

**Issue by pkzc** [mate-desktop/mate-applets#365]
#### Expected behaviour
Clean gauge images just with the graphs of the measured values.

#### Actual behaviour
Often, one or more white horizontal lines appear in the network traffic gauge.
![image](https://user-images.githubusercontent.com/23018794/47937084-f2f4c180-dedf-11e8-8707-265b3147ab8f.png)
![image](https://user-images.githubusercontent.com/23018794/47937378-d2793700-dee0-11e8-8d3a-42d96ce2b81a.png)
Also, a small blue patch is visible in the upper left corner, just like in the images.

#### Steps to reproduce the behaviour
Can't really figure out, but the glitch is present more often than not. Might be an interference with the disk data transfer gauge?

#### MATE general version
mate-desktop              1.20.3-1.fc28.x86_64

#### Package version
mate-applets              1.20.2-1.fc28.x86_64

#### Linux Distribution
Fedora 28

**Comment by marosg42** [comment]
Hi. These are not glitches, it is new feature to better show what is happening. Imagine your internet connectivity is up to 1Gbps. Multiload applet is several tens on points high. Lets say it is 100 points high. It means each point represents 10Mbps and that is your granularity of what you can see.

If you go to multiload preferences, there are three thresholds. When transfer speed reaches threshold 1, gridline appears together with one indicator (that small blue square, color is customizable in network section of preferences). When your transfer rate grows, you will get more gridlines up to reaching threshold2, then you get two indicators etc.

If you want the old behavior with less granularity, just change threshold1 value to whatever is your maximum internet speed and you will not see gridlines or indicators

Hope this helps

**Comment by pkzc** [comment]
My fault, I didn't notice the introduction of all this and the new configuration items.
I checked my config, Threshold1 is 1 Mb/s, Th2 = Th3 is 10 Mb/s.
Am I right to suppose that in the first picture I have transfer impulses of 1 to 1.8 Mb/s, while in the second one from 1 to 3.1 Mb/s?

**Comment by marosg42** [comment]
Right, you got the idea. One correction though - replace Mb with MB
