### ISSUE TITLE
Charpick (Character Palette) applet overlapping 

### ISSUE THREAD

**Issue by underwit** [mate-desktop/mate-applets#372]
Hello! I have a small bug with the Character Palette applet.

#### Expected behaviour
Normal display of buttons when switching them

![screenshottraditional](https://user-images.githubusercontent.com/951257/50340300-81261500-052b-11e9-9fe0-058623253eda.png)
(TraditionalOk desktop theme)

#### Actual behaviour
When switching sets, the buttons overlap each other.

![screenshot2](https://user-images.githubusercontent.com/951257/50340209-30162100-052b-11e9-9394-f2c89dc7e7ca.png)
![screenshot3](https://user-images.githubusercontent.com/951257/50340210-30162100-052b-11e9-8b40-638c8699666e.png)
![screenshot](https://user-images.githubusercontent.com/951257/50340211-30162100-052b-11e9-8dd5-729c765fc780.png)

#### Steps to reproduce the behaviour
1. Add Character Palette applet to panel
2. Choose one character set
3. Click on any char
4. Choose other character set

This bug appear in all desktop themes (from mate-themes) except TraditionalOk and TraditionalGreen.

#### MATE general version
1.20.3

#### Package version
mate-applets v1.20.2

#### Linux Distribution
ALT Linux Workstation 8.2
Mint 19

**Comment by lukefromdc** [comment]
This looks like yet another redraw issue in which the new images are just drawn over the old ones which also continue to be drawn. Any theme in which this does not occur may be drawing an opaque background for the button, which would cover up the previous image. 

Here's my guess as to what is happening: with GTK 3.22 and later, this sort of thing tends to come from the previous image having been somehow picked up as part of the background and added to it. An opaque background drawn anew covers it up.  This created major headaches in Caja development back in summer 2016, and several fixes (some requiring replacing deprecated functions) were utlimately required

**Comment by muktupavels** [comment]
Have you ever wondered if what you see is just side effect? Quickly looking at this I am pretty sure this has nothing to do with drawing/redrawing...

**Comment by ssrublev** [comment]
![image](https://user-images.githubusercontent.com/6886166/101146490-1b55c980-362c-11eb-8ef4-2914af560d49.png)

I see this too on several systems. It appeared long time ago and was discussed before. I am happy that the applet generally works and already have used to this bug. But I see it right now in Fedora-MATE (Ubuntu also has this). Overlapping appears after clicking, in not clicked, displays normally.

**Comment by balping** [comment]
Bug also occurs in Mate 1.24.1 on openSUSE Tumbleweed 

![over](https://user-images.githubusercontent.com/5840038/110251629-4af0d680-7f79-11eb-8247-fae1566cae84.png)

**Comment by balping** [comment]
I found a workaround by explicitly setting the background of the container box: #609
