### ISSUE TITLE
cpu-frequency broken in hidpi mode

### ISSUE THREAD

**Issue by allefant** [mate-desktop/mate-applets#378]
#### Expected behaviour
CPU frequency monitor icon is shown fully like with no hidpi scaling - it looks like this (just very tiny):

![image](https://user-images.githubusercontent.com/390841/52885792-5bd71100-3140-11e9-879c-92899b1de982.png)

#### Actual behaviour
CPU frequency icon is cut off, everything else looks fine but as you can see the cpu frequency icon is cut in half:

![image](https://user-images.githubusercontent.com/390841/52885824-7b6e3980-3140-11e9-858c-dd49d21ae14a.png)

#### Steps to reproduce the behaviour
Add the CPU frequeny scaling monitor to a panel, then switch Mate to hidpi - or be in hidpi mode already

#### MATE general version
1.20.3

#### Package version
mate-panel 1.20.3-1

#### Linux Distribution
Ubuntu 18.10

**Comment by raveit65** [comment]
Should be fixed with mate-1.22
![bildschirmfoto zu 2019-02-16 00-12-43](https://user-images.githubusercontent.com/961604/52889322-ab88fd00-317f-11e9-94d5-d7edf13f57c5.png)

**Comment by raveit65** [comment]
I think by this commit
https://github.com/mate-desktop/mate-applets/commit/7185a704026f9fccf253c0993be986d359f16526

**Comment by raveit65** [comment]
@vkareh 
Can you confirm that you have fixed it already?

**Comment by vkareh** [comment]
It's fixed, but it was actually fixed by 8bd11f81e05d8498c530e3951fa0f1c2b67a74b8

**Comment by raveit65** [comment]
@vkareh 
Maybe this should be cherry-picked to 1.20 if possible?
