### ISSUE TITLE
mateweather doc build segmentation fautl with itstool (With Template)

### ISSUE THREAD

**Issue by jmrcpn** [mate-desktop/mate-applets#388]
#### Expected behaviour
Successful Build

#### Actual behaviour
Crash
segmentation fault itstool -m "${mo}" ${d}/C/index.docbook ${d}/C/legal.xml

The problem was pin-point to be within
mate-applets-1.22.0/mateweather/docs/ru/ru.po
replacing ru.po by uk/uk.po (Ukrainian, roughly the same alphabet), make everything compiled.
With a naked eye, the ru.po seems to be quite normal (not a Russian speaking).
I do not believe it is a compilation workbench problem (itstool libraries), as all other foreign documentation (fr,it,zh,zu,etc.) are done without trouble.

#### Steps to reproduce the behaviour
Build (configure + make)

#### MATE general version
1.22.0

#### Package version
1.22.0

#### Linux Distribution
OSUKISS

#### Link to downstream report of your Distribution
I am the distribution builder

**Comment by raveit65** [comment]
Thanks for honor the template.
It's a known issue with newer itstools.
see https://github.com/mate-desktop/mate-utils/issues/210
https://github.com/itstool/itstool/issues/36
and caused by https://github.com/itstool/itstool/commit/d3adf0264ee2b6fd28b7eff7dec33501d6e75a7c
You can try starting the build again, sometimes this helps and you will be lucky after starting it 4-8 times.
For fedora i use this workaround to disable the culprit language in make file, as i am building for different architectures and it fails always.
https://src.fedoraproject.org/cgit/rpms/mate-utils.git/commit/

**Comment by jmrcpn** [comment]
On 03/16/2019 12:00 PM, raveit65 wrote:
> Thanks for honor the template.
> It's a known issue with newer itstools.
> see mate-desktop/mate-utils#210
> <https://github.com/mate-desktop/mate-utils/issues/210>
> itstool/itstool#36 <https://github.com/itstool/itstool/issues/36>
> and caused by itstool/itstool@d3adf02
> <https://github.com/itstool/itstool/commit/d3adf0264ee2b6fd28b7eff7dec33501d6e75a7c>
> You can try starting the build again, sometimes this helps and you will
> be lucky after starting it 4-8 times.
> For fedora i use this workaround to disable the culprit language in make
> file, as i am building for different architectures and it fails always.
> https://src.fedoraproject.org/cgit/rpms/mate-utils.git/commit/
>
I have done multiple rebuild when trying to define the
exact trouble.
Expecting "to be Lucky" by building many time
(timing or context issues) is not an option.

Tools used to make build ares
gcc-8.3
itstool-2.0.5
intltool-0.51.0
libmateweather-1.22.0

Problem is indeed within file
mateweather/docs/ru/ru.po
As all other languages (>120) are
translated properly, It safe to say
it is a transifex(ru) problem.

You are in better position than me, to ask/report to
the transifex teams about a ru.po possible
file format small glitch.
Right, itstool should report a "in trouble"
and line number, rather to crash.

In  mid time, I am  replacing ru.po with uk.po
within spec file build sequence (not nice, nor perfect...)

-- 
seen "Linux from scratch" and looking for ISO files
www.osukiss.org

**Comment by raveit65** [comment]
Sorry, we can`t help. Problem isn't in .pot file, as i said it's a bug in itstools with using parallel builds.
Please read links and follow my suggestion to disable the language.
Or patch itstools, simply revert https://github.com/itstool/itstool/commit/d3adf0264ee2b6fd28b7eff7dec33501d6e75a7c
I am waiting for myself of a reaction by itstools developer since 2 months.

**Comment by jmrcpn** [comment]
On 03/16/2019 03:18 PM, raveit65 wrote:
> Sorry, we can`t help. Problem isn't in .pot file, as i said it's a bug
> in itstools with using parallel builds.
> Please read links and follow my suggestion to disable the language.
> Or patch itstools, simply revert itstool/itstool@d3adf02
> <https://github.com/itstool/itstool/commit/d3adf0264ee2b6fd28b7eff7dec33501d6e75a7c>
> I am waiting for myself of a reaction by itstools developer since 2 months.
>
Sorry, I do not confirm

There is a bit of misunderstanding here.
I have done the itstool command manually (extracted
from the Makefile itself)

- Crash is happening all time ONLY with ru.po (manual mode)
- Replacing ru.po (everything equal otherwise) make the
   itstool NOT to crash. And such; in Manual mode AND within
   "massive build", (make -j28)

I have no indication within itstool manual, about
"parallel conversion/translation".
(Am I missing something?).

I have no indication the itstool crash could be induced
via "./configure" options.

itstool-2.0.5 may have a problem, but "my" build is
NOT saying so. This could explain why you have
no reaction from "itstools developer since 2 months".

I have "disabled language", but this is hiding the
mate-applets+libmateweather problem (true, it is
Not a MATE problem as such as MATE is using
transifex(ru))

Hoping my "homework" report, clarify why
I (still) think the reported problem is not
a itstool as such.

-- 
seen "Linux from scratch" and looking for ISO files
www.osukiss.org

**Comment by jmrcpn** [comment]
Many Thanks rubj, extracted the 3 ru.po from your commit and the build is now  going flawless...
Please, Make sure your "ru-xml" branch will be merged with master. 
Note:  So itstool is unable to recover to a very simple parsing problem/anomaly....
:) itstool team!?... there is room for improvement ;)

**Comment by rbuj** [comment]
https://github.com/mate-desktop/mate-applets/commit/f3654da400e936dbc2f52b40c9a1869d2f5e46eb closes the issue in [master](https://github.com/mate-desktop/mate-applets/tree/master) branch.
https://github.com/mate-desktop/mate-applets/commit/c2db44280ef7aebdca6c62a6f39f0bbe2c1200da closes the issue in [1.22](https://github.com/mate-desktop/mate-applets/tree/1.22) branch.
https://github.com/mate-desktop/mate-applets/commit/de7e44719c3613cd82f344c3b498065aa84e4cf2 closes the issue in [1.20](https://github.com/mate-desktop/mate-applets/tree/1.20) branch.
