### ISSUE TITLE
Applet icon in "Show Desktop" all the time is stretched

### ISSUE THREAD

**Issue by dkslad** [mate-desktop/mate-applets#39]
![show-desktop-applet](https://f.cloud.github.com/assets/4086972/349524/ea7d1a74-9fcb-11e2-8c1e-4aacf33be68e.png)

Example:
1. sudo apt-get install hedgewars
2. Icon at the Show Desktop applet stretch

http://forums.linuxmint.com/viewtopic.php?f=206&p=706574

Linux Mint 14 64-bit, MATE 1.4.2

**Comment by NiceandGently** [comment]
@monsta 
no answere since over an year, should be closed.

**Comment by flexiondotorg** [comment]
Closing this now. If new information is made available we can reopen it.
