### ISSUE TITLE
How to add a applet to my pc or How to modify the applet

### ISSUE THREAD

**Issue by lzxZz** [mate-desktop/mate-applets#390]
Hello
Mate is the best Desktop which i have used. Especially the applet.

Now I have some idea to modify some applet like mateweather, It can't work on my pc. 

So that I only use the command to display the weather, I want to modify the applet. 

And I have a problem that I don't known how to apply the modify to my pc. Can you give some material?

**Comment by lukefromdc** [comment]
The applets are written in C. First thing is to be able to compile and install them locally from the existing source. Then start looking at the source, and look for the functions you want to make changes in or the appropriate places to add new features. Do remember that C is less tolerant of memory management problems (especially in string handling) than languages like Python or Javascript, as you are working at a lower level with the hardware.

**Comment by lzxZz** [comment]
I known this step, I can't find the applet program in my pc(I had run `find / -name netspped` but nothing), so I can't replace the binary file to install. Do I need recompile the os?

**Comment by lzxZz** [comment]
Maybe I need make and make install?

**Comment by lukefromdc** [comment]
Yes you do, in Debian you get both of these from the "build-essential" package.

**Comment by mbkma** [comment]
See https://wiki.mate-desktop.org/ for details.
