### ISSUE TITLE
Weather report has a big gap between icon and temperature

### ISSUE THREAD

**Issue by nivag** [mate-desktop/mate-applets#395]
#### Expected behaviour
minimal gap between weather icon & temperature

#### Actual behaviour
Large gap between weather icon & temperature,
icon & temp seem to be centred at 25% & 75% of size:
[..icon....temp..]

#### Steps to reproduce the behaviour
1. set size of panel large enough, 64 should be enough
2. ensure there is a instance of the Mate Weather Report

#### MATE general version
1.22

#### Package version
1.22.1

#### Linux Distribution
Fedora 29 & 30

#### Link to downstream report of your Distribution
Bug 1707345

**Comment by raveit65** [comment]
I can confirm the gap.
![Bildschirmfoto zu 2019-05-08 11-43-41](https://user-images.githubusercontent.com/961604/57366134-b3f14280-7186-11e9-9fdc-6c752dcda37e.png)

**Comment by raveit65** [comment]
@nivag 
Feel free to test PR.

**Comment by raveit65** [comment]
@nivag 
Here are builds for f29/30 with that fix.
https://koji.fedoraproject.org/koji/taskinfo?taskID=34724147
https://koji.fedoraproject.org/koji/taskinfo?taskID=34724156

**Comment by nivag** [comment]
F30 build fixes problem, (taskID=34724147)

However,
https://koji.fedoraproject.org/koji/taskinfo?taskID=34724156
claims to be an F29 build, but is actually an F30 build!

**Comment by nivag** [comment]
F29 rpm update fixes problem
Thanks!
