### ISSUE TITLE
Migrate from libiw to libnl

### ISSUE THREAD

**Issue by nullr0ute** [mate-desktop/mate-applets#400]
#### Expected behaviour
Replace use of libiw with libnl for netspeed applet. The wireless-tools is long obsolete and doesn't support details of newer adapters, the replacement is libnl [1] so using that to get stats is better. Also it should be able to be used for stats of all network interfaces, not just wireless, so likely will make things more consistent.

[1] https://wireless.wiki.kernel.org/en/users/Documentation/iw

#### MATE general version
1.22

#### Package version
mate-applets-1.22.1

#### Linux Distribution
Fedora

**Comment by raveit65** [comment]
Thanks for reporting this.
Is there a plan to remove wireless-tools package from fedora?

**Comment by raveit65** [comment]
Fixed, https://github.com/mate-desktop/mate-applets/commit/bff29f926f56aba490e3f7b6f2d11e6a1aae46c7

**Comment by nullr0ute** [comment]
awesome, thanks. The plan is to move towards removing it from Fedora because it primarily only does old more insecure wireless protocols and is no longer as widely used.
