### ISSUE TITLE
CPU Frequency Scaling Monitor disappeared and cannot be added to panel

### ISSUE THREAD

**Issue by adatum** [mate-desktop/mate-applets#408]
#### Expected behaviour
CPU Frequency Scaling Monitor applet should appear on panel if added

#### Actual behaviour
CPU Frequency Scaling Monitor applet which was previously added no longer appears on the panel, and cannot be added

#### Steps to reproduce the behaviour
Right-click the mate panel, select Add to Panel, select CPU Frequency Scaling Monitor from the applet list. It does not appear anywhere. 

#### MATE general version
1.22.1

#### Package version
1.22.1

#### Linux Distribution
Fedora 30

---

I have been using this applet for a long time and just realized (perhaps since the past few days/weeks, not quite sure) that the applet no longer appears when I start my system. Attempting to add the applet also fails.

**Comment by raveit65** [comment]
Support for kernel-5.1.0 is already added to mate-applets-1.22.1-3.fc30.
https://koji.fedoraproject.org/koji/buildinfo?buildID=1288163
Please update!

**Comment by adatum** [comment]
Thanks! You're right I'm on release 2.fc30 and my system is up to date. Hopefully release 3.fc30 becomes available soon through system updates. I'll let you know if that fixes the problem.

**Comment by raveit65** [comment]
`dnf config-manager --enable updates-testing && dnf update mate-applets && dnf config-manager --disable updates-testing`

**Comment by adatum** [comment]
I can confirm `mate-applets-1.22.1-3.fc30` fixes the problem. Thank you!
