### ISSUE TITLE
Volume applet disappears when mouse is used 

### ISSUE THREAD

**Issue by nickwinlund** [mate-desktop/mate-applets#410]
## Expected behaviour

Volume indicator adjustment

#### Actual behaviour

Volume indicator disappears when mouse is used on it

#### MATE general version

marco 1.20.1

#### Linux Distribution

Linux Mint 19.1

===================================================================
 GDB Log                                                           
===================================================================

warning: core file may not match specified executable file.
[New LWP 2091]
[New LWP 2103]
[New LWP 2099]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `mate-volume-control-applet'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f3dd7d89f00 (LWP 2091))]

**Comment by lukefromdc** [comment]
The volume control status icon (or beginning with mate-media 1.23 and might have been backported to 1.22 an alternate tray icon with better hidpi support) is provided by mate-media, not mate-applets. If you are discussing a sound indicator that would be Ubuntu's indicator-sound package which is not one or ours. 

What is the name of the process you were running under GDB or attaching GDB to?  That would tell me whether this is mate-media's mate-volume-control-applet (as it is called in MATE 1.20) or something else. If it is  mate-volume-control-applet you will need to open an issue in mate-media as we have no way to migrate an issue to a different package. If it is Ubuntu's indicator-sound you will need to open an issue with them. In either case this is the wrong package so closing this one.
