### ISSUE TITLE
Workspace Switcher confused

### ISSUE THREAD

**Issue by ajfre** [mate-desktop/mate-applets#417]
#### Expected behaviour
Dialog Windows, which are not "Always on Visible Workspace" should disappear on a workspace switch.

#### Actual behaviour
The dialog window also appears after switching the workspace and the application itself appears minized in the tray of the new workspace.
After closing the dialog window, the application cannot be unminimized.
Switching back to the former workspace, the app has completely disappeared there.
Switching back once more shows the app unminimized.

#### Steps to reproduce the behaviour
1. Start synaptic in workspace 3
2. click search - the search dialog opens
3. switch to workspace 5 - the search dialog appears and synaptic is minimized
4. close the search dialog
5. try to unminimize synaptic - it dosn't unminimize
6. switch to workspace 3 - there is no synaptic any more
7. switch back to ws 5 - synaptic is unminimized

Synaptic is only an example, the issue can also be reproduced with caja's copy file progress dialog.

See the attached screencast
[Screencast 2019-09-05 01:53:45.mp4.zip](https://github.com/mate-desktop/mate-applets/files/3576920/Screencast.2019-09-05.01.53.45.mp4.zip)

#### MATE general version
Don't know where to find the version ID. I reproduced the issue on Ubuntu Mate 18.04.3, Linux Mint 19.1 and 19.2

#### Linux Distribution
Ubuntu Mate 18.04.3, Linux Mint 19.1 and 19.2

**Comment by lukefromdc** [comment]
This is a window management bug and thus a marco issue. We have no way to migrate this from mate-applets to marco, so closing this one. Please open a new issue (can be the same text) against marco.  BTW, I've also seen this issue with synaptic (and even had the same bug in compiz on some machines and not others) , so it may relate to a specific option in how it's dialog windows are called.
