### ISSUE TITLE
[Feature Request] Clipman-like clipboard manager Mate panel plugin.

### ISSUE THREAD

**Issue by LinuxJoeUser** [mate-desktop/mate-applets#422]
An issue search turned up nothing since this was requested in 2014.  At that time the requester was pointed to a list of clipboard managers at the Arch wiki.  I'd like to make an entirely new request, specifically for a dedicated Mate panel plugin that the user finds when clicking the "Add to Panel" list when right clicking on the panel itself.

**Comment by flexiondotorg** [comment]
There are several high quality clipboard managers for GTK desktops. We don't need to take on the burden on maintaining our own when good choices already exist 👍
