### ISSUE TITLE
Netspeed applet ignores signal quality display choice

### ISSUE THREAD

**Issue by patricktokeeffe** [mate-desktop/mate-applets#429]
Hi, I observe a minor rendering issue with the `mate-netspeed` applet 1.16.0-1~xenial3.1 (Ubuntu MATE 16.04 LTS minimal desktop on RPi3). This may have been fixed since 1.16 but I found no related issues.

The wifi signal quality icon will be rendered when the <kbd>Show sum instead of in & out</kbd> option is modified, even if the <kbd>Show signal quality icon for wireless devices</kbd> option is disabled:

![image](https://user-images.githubusercontent.com/1348834/65989196-0e44b580-e43e-11e9-9fef-5fc0b03d0601.png)

![image](https://user-images.githubusercontent.com/1348834/65989203-143a9680-e43e-11e9-8983-4b1725447d5c.png)

![image](https://user-images.githubusercontent.com/1348834/65989211-17ce1d80-e43e-11e9-8f73-875b93ff3fe6.png)

**Comment by flexiondotorg** [comment]
Sorry, Ubuntu 16.04 and MATE Desktop 1.16 are both no longer supported. There are images of Ubuntu MATE 18.04 for the Pi though.

  * https://ubuntu-mate.org/raspberry-pi/
