### ISSUE TITLE
Inverted mouse wheel sound controll behavior

### ISSUE THREAD

**Issue by felipevencato** [mate-desktop/mate-applets#465]
#### Expected behavior
Consistent mouse wheel behavior to adjust sound

#### Actual behavior
The mouse wheel behavior changes depending if you are hovering the mouse over the sound icon on the bar or in the sound slider on the sound menu.

#### Steps to reproduce the behavior
When you hover the mouse over the sound icon on the bar, the mouse wheel behave as expected. Up increases the volume and down decreases the volume. When you click on de sound icon and move the mouse to hover over the sound slider, the behavior is reversed, up decreases the volume and down increases the volume.

#### MATE general version
 1.24.0

#### Package version
1.24.0

#### Linux Distribution
Ubuntu Mate 20.04

#### Link to downstream report of your Distribution
??

**Comment by raveit65** [comment]
> When you click on de sound icon and move the mouse to hover over the sound slider, the behavior is reversed, up decreases the volume and down increases the volume.

The sound menu is from Ubuntu not from Mate desktop.

> #### Link to downstream report of your Distribution
??

Exactly for this reason we ask you to file out a report against upstream=Ubuntu.
