### ISSUE TITLE
Question about coding a PR

### ISSUE THREAD

**Issue by tamplan** [mate-desktop/mate-applets#474]
I think no need to use template.

I have seen different icons betwwen windows list, netrspeed and accessx-status applets :
![Capture du 2020-06-26 09-18-38](https://user-images.githubusercontent.com/50292710/85839465-41cd2a00-b79b-11ea-9af0-bcdc9b1c0b53.png)

I would like to change the icon of the accessx-status applet, no problem for the icon but i would like to change text label too.
The problem is if i like to change 'Preferences...' to '_Preferences' or 'About...' to '_About'.

I have made changes here https://github.com/mate-desktop/mate-applets/compare/master...tamplan:harmonize

The changes involve change about po files.

How can i do this?

Thanks by advance.

Regards.

**Comment by rbuj** [comment]
Updates to translation files are made periodically by maintainers, however you can check it locally by generating the pot file, updating and translating the po file corresponding to your language, and installing it on your system.

In this case this will help you review the keyboard accelerators, which are also called keyboard mnemonics, in your language.

**Comment by tamplan** [comment]
My question was about files to push, i think i don't need to push .po~ files (backup copy i presume).

Has you read the files changes in the link i give?

I need to push source code files changed, pot file and po file for all language, just to be sure.

raveit65 indicates me to push po files modified also in github for tracking.

**Comment by raveit65** [comment]
> raveit65 indicates me to push po files modified also in github for tracking.

NO NO NO, i didn't say that.
Please do not touch *.po files or *.pot files.
We do that for ourself.

**Comment by tamplan** [comment]
Ok, i was not understood that.

In that case, i just push source code files indicating the change is about translation.

**Comment by rbuj** [comment]
It wasn't an issue, it was a doubt and it was answered.
