### ISSUE TITLE
 charpick.c:518:3: warning: Potential leak of memory pointed to by 'row_box'

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-applets#526]
#### Expected behaviour
Travis builds whether successful or not don't generate warnings about potential memory leaks

#### Actual behaviour
A  build at 
https://travis-ci.org/github/mate-desktop/mate-applets/jobs/710021076
failed for other reasons, looking at the logs I noticed this warning(not the cause of the build failure):

charpick.c:518:3: warning: Potential leak of memory pointed to by 'row_box'
```

  g_free (toggle_button);
```

#### Steps to reproduce the behaviour
Unsure: this is Travis. Replicate the conditions of 
https://travis-ci.org/github/mate-desktop/mate-applets/builds/710021074
should do it though

#### MATE general version
1.25.0

#### Package version
Travis job 689.2

#### Linux Distribution
Debian testing

#### Link to downstream report of your Distribution
None, this is a Travis build

**Comment by mbkma** [comment]
Fixed https://github.com/mate-desktop/mate-applets/pull/503/files
