### ISSUE TITLE
netspeed applet shows incorrect download speeds

### ISSUE THREAD

**Issue by jparsons2222** [mate-desktop/mate-applets#527]
#### Expected behaviour
Until June 2020, Mate-applets netspeed applets used to show correct up and down speeds in digits and the numbers concurred with application speed measurements

#### Actual behaviour
After July 2020, Mate-applets netspeed applets shows low random numbers for download speeds independent of actual network performance. Also, the network indicator applet seems to get stuck on Ethernet symbol even when the WiFi is being used instead

#### Steps to reproduce the behaviour
Start an Ubuntu Mate session on Ethernet or WiFi connection

#### Package version
ii  mate-applet-appmenu                        0.7.3+dfsg1-2                         amd64        Application Menu plugin for mate-panel
ii  mate-applet-brisk-menu                     0.6.0-1ubuntu1                        amd64        Solus Project's Brisk Menu MATE Panel Applet
ii  mate-applets                               1.24.0-1                              amd64        Various applets for the MATE panel
ii  mate-applets-common                        1.24.0-1                              all          Various applets for the MATE panel (common files)

Linux quad 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

#### Linux Distribution
Ubuntu Mate 20.04

**Comment by rbuj** [comment]
Did you use any traffic capture tools to check the results like Wireshark IO Graphs? Perhaps, there is more traffic than you think on your network.

**Comment by jparsons2222** [comment]
No, I suspect that the problem was actually NetworkManager switching from Ethernet to WiFi connection but leaving the connection icon and netspeed applet monitoring the wrong/old connection.
