### ISSUE TITLE
Horizontal lines and blue squares in the network usage of the system monitor applet

### ISSUE THREAD

**Issue by samuel-phan** [mate-desktop/mate-applets#533]
#### Expected behaviour
Display the network usage in the system monitor applet without the horizontal lines or the blue squares.

#### Actual behaviour
There are horizontal lines and blue squared displayed in the network usage of the system monitor applet.
![image](https://user-images.githubusercontent.com/1516171/96038420-62fb7880-0e67-11eb-9989-d187d14ecf71.png)

#### Steps to reproduce the behaviour
- Right-click on one of the MATE panel > Add to panel > System monitor.
- Right-click on the system monitor applet > Preferences.
- Check Memory and Network.
![image](https://user-images.githubusercontent.com/1516171/96038485-7d355680-0e67-11eb-8f5d-11045f15048f.png)
- Use your bandwidth like open your web browser on Youtube and make sure to reload the page with bypassing cache (Ctrl+Shift+R).

If you need to reproduce it once you have the system monitor applet, you can do this:
- Right-click on the system monitor applet > Preferences.
- Uncheck Memory and Network.
- Check Memory and Network back.
- Use your bandwidth like open your web browser on Youtube and make sure to reload the page with bypassing cache (Ctrl+Shift+R).

#### MATE general version
1.24.0

#### Package version
```
ii  mate-system-monitor                        1.24.0-1                              amd64        Process viewer and system resource monitor for MATE
ii  mate-system-monitor-common                 1.24.0-1                              all          Process viewer and system resource monitor for MATE (common files)
```

#### Linux Distribution
```
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```

#### Link to downstream report of your Distribution
N/A.

**Comment by rbuj** [comment]
setting higher network thresholds will not show horizontal lines or the level indicator on the network chart

**Comment by samuel-phan** [comment]
All right, I just understood :sweat_smile: These horizontal lines and blue square are not a bug: it's a feature to have an idea of the scale up or down of your bandwidth.

![image](https://user-images.githubusercontent.com/1516171/96189951-b5a96300-0f41-11eb-8d45-016f3eb84484.png)

Thanks, @rbuj , sorry for the trouble.
