### ISSUE TITLE
netspeed: support IPv6 in tooltip window

### ISSUE THREAD

**Issue by treysis** [mate-desktop/mate-applets#557]
#### Expected behaviour

When hovering the applet in the status bar, it should show the IPv6 address of the NIC in the tooltip window.

#### Actual behaviour

When hovering the applet in the status bar, it only shows the legacy IPv4 address. If no legacy address is configured on that interface, it will only show "0.0.0.0" in the tooltip window.

#### Steps to reproduce the behaviour

Configure interface with IPv6 address. Add netspeed applet to taskbar. Hover it with the mouse for the tooltip window to appear.

#### MATE general version

MATE Desktop Environment 1.24.0

#### Package version

MATE Netspeed 1.24.0

#### Linux Distribution

Mint 20 MATE 64-bit

**Comment by treysis** [comment]
Request to reopen!

https://github.com/mate-desktop/mate-applets/pull/558/commits/658f4e84328ce1918f59b9330fb5d1abd7b5830e only partially fixes it. This will show IPv6 only if no IPv4 is configured. However, in case of dualstack (i.e. both IPv4 and IPv6 being configured) it should show both IP addresses. Well, since I haven't tried it, I don't even know which of the several IPv6 addresses an interface can have will be chosen!

**Comment by raveit65** [comment]
Re-opened..

**Comment by rbuj** [comment]
The information displayed on the tooltip makes only sense to quickly identify the interface.
Displaying both ip addresses would make it difficult to identify the interface, as the IPv6 address is usually used as local link.
If you want further information about the interface you can click on `Device Details`.

**Comment by treysis** [comment]
But sometimes - especially on a network-centric OS - people focus more on IPv6 than IPv4. So in any way it would make sense to display both address types. Or just leave out the address and just identify the interface by its interface name (e.g. `eth1`). However, I think having the IP in the tooltip is better, and to make it perfect it should show all IPs, i.e. IPv4, IPv6-LL, IPv6, IPv6-PE, IPv6-ULA, the same way as for example Android shows on the "About" screen.

**Comment by raveit65** [comment]
> .....and to make it perfect it should show all IPs, i.e. IPv4, IPv6-LL, IPv6, IPv6-PE, IPv6-ULA, the same way as for example Android shows on the "About" screen.

I think showing both ip4 and ip6 address, if it is easy to add, should be enough. It is a tooltip and not a device interface page.

Btw. you can show everything you want from a script in the panel with our command line interface.

I disabled ipv6 for a while in my small local network, but i agree that some people like to use it.

**Comment by rbuj** [comment]
I added IPv6 scope in device details on #564. The scope6 value is pulled from libgtop [1] using IN macros [2].

I don't know whether it's a good idea to show both ip addresses on the tooltip, however users should be able to activate it on the preferences dialog via gsettings. I'm going to code it.

[1] https://github.com/GNOME/libgtop/blob/7e214414bf23d1ea34e7fdccb17a7f41040ffea9/sysdeps/linux/netload.c#L127
[2] https://pubs.opengroup.org/onlinepubs/009695399/basedefs/netinet/in.h.html

**Comment by raveit65** [comment]
> I don't know whether it's a good idea to show both ip addresses on the tooltip, however users should be able to activate it on the preferences dialog via gsettings. I'm going to code it.

@rbuj 
I had started to fix code-style for netspeed applet. It's not a huge commit like the others. Can we wait a little bit to avoid conflicting PRs?

**Comment by rbuj** [comment]
> > I don't know whether it's a good idea to show both ip addresses on the tooltip, however users should be able to activate it on the preferences dialog via gsettings. I'm going to code it.
> 
> @rbuj
> I had started to fix code-style yesterday for netspeed applet. It's not a huge commit like with other applets. Can we wait a little bit to avoid conflicting PRs?
> 
> Edit: Or should i wait?

@raveit65 OK, I marked #564 as WIP. Format the code first and then I will update the PR.

**Comment by treysis** [comment]
Looks much better so far. Though I'd probably exchange the field for `IPv6 Prefix` by just appending the prefix length to the IPv6 address? E.g. `/64`.
Also wondering if it should show the scope ID for link local addresses? I.e. `fe80::1234:56ff:fe78:90ab%enp0s3`
Not so sure if I would include the `IPv6 Scope` field...I'd probably prefer one line for each IPv6. And I would do the same in the tooltip: first line IPv4, and below one line for each IPv6.

**Comment by rbuj** [comment]
@treysis `/64` is a IPv6 [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) for subneting (ffff:ffff:ffff:ffff), like /24 on IPv4 (255.255.255.0).

**Comment by treysis** [comment]
I know. It's just more common with IPv6 and also space preserving, especially if we think about displaying multiple IPv6 addresses in that window.

**Comment by treysis** [comment]
Can you even iterate through `applet->devinfo->ipv6`?

**Comment by rbuj** [comment]
Broadly speaking, netspeed uses libgtop to collect information from networking, as it supports several operating systems. [Net List](https://developer.gnome.org/libgtop/stable/libgtop-Net-List.html) to get the interfaces and [Net Load](https://developer.gnome.org/libgtop/stable/libgtop-Net-Load.html) to get the interface information.

**Comment by treysis** [comment]
Well, it seems like Net Load hasn't been fixed to support more than one IPv6 address in the last 12 years:
https://gitlab.gnome.org/GNOME/libgtop/-/issues/12
https://gitlab.gnome.org/GNOME/libgtop/-/issues/13

Or am I missing something?

**Comment by rbuj** [comment]
ifconfig (net-tools) parses `/proc/net/if_inet6` file and gets all ipv6 addresses (`addr6p`) for an iface (`ptr->name`) on Linux:
```C
#if HAVE_AFINET6
    /* FIXME: should be integrated into interface.c.   */

    if ((f = fopen(_PATH_PROCNET_IFINET6, "r")) != NULL) {
        while (fscanf(f, "%4s%4s%4s%4s%4s%4s%4s%4s %08x %02x %02x %02x %20s\n",
                      addr6p[0], addr6p[1], addr6p[2], addr6p[3],
                      addr6p[4], addr6p[5], addr6p[6], addr6p[7],
                  &if_idx, &plen, &scope, &dad_status, devname) != EOF) {
            if (!strcmp(devname, ptr->name)) {
                sprintf(addr6, "%s:%s:%s:%s:%s:%s:%s:%s",
                        addr6p[0], addr6p[1], addr6p[2], addr6p[3],
                        addr6p[4], addr6p[5], addr6p[6], addr6p[7]);
                inet6_aftype.input(1, addr6, &sas);
                printf(_("        %s %s  prefixlen %d"),
                        inet6_aftype.name,
                        inet6_aftype.sprint(&sas, 1),
                        plen);
                printf(_("  scopeid 0x%x"), scope);

                flags[0] = '<'; flags[1] = 0;
                if (scope & IPV6_ADDR_COMPATv4) {
                        strcat(flags, _("compat,"));
                        scope -= IPV6_ADDR_COMPATv4;
                }
                if (scope == 0)
                        strcat(flags, _("global,"));
                if (scope & IPV6_ADDR_LINKLOCAL)
                        strcat(flags, _("link,"));
                if (scope & IPV6_ADDR_SITELOCAL)
                        strcat(flags, _("site,"));
                if (scope & IPV6_ADDR_LOOPBACK)
                        strcat(flags, _("host,"));
                if (flags[strlen(flags)-1] == ',')
                        flags[strlen(flags)-1] = '>';
                else
                    	flags[strlen(flags)-1] = 0;
                printf("%s\n", flags);
            }
        }
        fclose(f);
    }
#endif
```
https://sourceforge.net/p/net-tools/code/ci/master/tree/lib/interface.c

**Comment by treysis** [comment]
But as far as I understand glibtop/netload uses `getifaddrs` directly. I seem to understand that my C has gotten too rusty to understand how to iterate over the whole structure :/

from `netload.c`:
```
static void get_ipv6(glibtop *server, glibtop_netload *buf,
		     const char *interface)
{
	struct ifaddrs *ifa0, *ifr6;

	if(getifaddrs (&ifa0) != 0)
	{
		glibtop_warn_r(server, "getifaddrs failed : %s", g_strerror(errno));
		return;
	}

	for (ifr6 = ifa0; ifr6; ifr6 = ifr6->ifa_next) {
		if (strcmp (ifr6->ifa_name, interface) == 0
		    && ifr6->ifa_addr != NULL
		    && ifr6->ifa_addr->sa_family == AF_INET6)
			break;
	}

	if(!ifr6) goto free_ipv6;

	memcpy(buf->address6,
	       &((struct sockaddr_in6 *) ifr6->ifa_addr)->sin6_addr,
	       16);

	memcpy(buf->prefix6,
	       &((struct sockaddr_in6 *) ifr6->ifa_netmask)->sin6_addr,
	       16);


	if (IN6_IS_ADDR_LINKLOCAL (buf->address6))
		buf->scope6 = GLIBTOP_IF_IN6_SCOPE_LINK;

	else if (IN6_IS_ADDR_SITELOCAL (buf->address6))
		buf->scope6 = GLIBTOP_IF_IN6_SCOPE_SITE;

	else if (IN6_IS_ADDR_GLOBAL (buf->address6)
		 || IN6_IS_ADDR_MC_ORGLOCAL (buf->address6)
		 || IN6_IS_ADDR_V4COMPAT (buf->address6)
		 || IN6_IS_ADDR_MULTICAST (buf->address6)
		 || IN6_IS_ADDR_UNSPECIFIED (buf->address6)
		)
		buf->scope6 = GLIBTOP_IF_IN6_SCOPE_GLOBAL;

	else if (IN6_IS_ADDR_LOOPBACK (buf->address6))
		buf->scope6 = GLIBTOP_IF_IN6_SCOPE_HOST;

	else
		buf->scope6 = GLIBTOP_IF_IN6_SCOPE_UNKNOWN;

	buf->flags |= _glibtop_sysdeps_netload_6;

 free_ipv6:
	freeifaddrs(ifa0);
}
```

**Comment by rbuj** [comment]
Yes, you can get all AF_INET6 addresses for a device using [getifaddrs](https://man7.org/linux/man-pages/man3/getifaddrs.3.html):
(code included on the manual)
```C
       #define _GNU_SOURCE     /* To get defns of NI_MAXSERV and NI_MAXHOST */
       #include <arpa/inet.h>
       #include <sys/socket.h>
       #include <netdb.h>
       #include <ifaddrs.h>
       #include <stdio.h>
       #include <stdlib.h>
       #include <unistd.h>
       #include <linux/if_link.h>

       int main(int argc, char *argv[])
       {
           struct ifaddrs *ifaddr;
           int family, s;
           char host[NI_MAXHOST];

           if (getifaddrs(&ifaddr) == -1) {
               perror("getifaddrs");
               exit(EXIT_FAILURE);
           }

           /* Walk through linked list, maintaining head pointer so we
              can free list later */

           for (struct ifaddrs *ifa = ifaddr; ifa != NULL;
                    ifa = ifa->ifa_next) {
               if (ifa->ifa_addr == NULL)
                   continue;

               family = ifa->ifa_addr->sa_family;

               /* Display interface name and family (including symbolic
                  form of the latter for the common families) */

               printf("%-8s %s (%d)\n",
                      ifa->ifa_name,
                      (family == AF_PACKET) ? "AF_PACKET" :
                      (family == AF_INET) ? "AF_INET" :
                      (family == AF_INET6) ? "AF_INET6" : "???",
                      family);

               /* For an AF_INET* interface address, display the address */

               if (family == AF_INET || family == AF_INET6) {
                   s = getnameinfo(ifa->ifa_addr,
                           (family == AF_INET) ? sizeof(struct sockaddr_in) :
                                                 sizeof(struct sockaddr_in6),
                           host, NI_MAXHOST,
                           NULL, 0, NI_NUMERICHOST);
                   if (s != 0) {
                       printf("getnameinfo() failed: %s\n", gai_strerror(s));
                       exit(EXIT_FAILURE);
                   }

                   printf("\t\taddress: <%s>\n", host);

               } else if (family == AF_PACKET && ifa->ifa_data != NULL) {
                   struct rtnl_link_stats *stats = ifa->ifa_data;

                   printf("\t\ttx_packets = %10u; rx_packets = %10u\n"
                          "\t\ttx_bytes   = %10u; rx_bytes   = %10u\n",
                          stats->tx_packets, stats->rx_packets,
                          stats->tx_bytes, stats->rx_bytes);
               }
           }

           freeifaddrs(ifaddr);
           exit(EXIT_SUCCESS);
       }
```
In the example below, the enp0s8 interface has 2 ipv6 addresses:
- inet6 fe80::a00:27ff:fe3e:199f  prefixlen 64  scopeid 0x20<link>
- inet6 2001:1310:8122:2::1  prefixlen 48  scopeid 0x0<global>

```
$ ./a.out 
lo       AF_PACKET (17)
		tx_packets =         10; rx_packets =         10
		tx_bytes   =       1564; rx_bytes   =       1564
enp0s3   AF_PACKET (17)
		tx_packets =        183; rx_packets =        278
		tx_bytes   =      27418; rx_bytes   =      32267
enp0s8   AF_PACKET (17)
		tx_packets =         10; rx_packets =          0
		tx_bytes   =       1290; rx_bytes   =          0
lo       AF_INET (2)
		address: <127.0.0.1>
enp0s3   AF_INET (2)
		address: <192.168.1.9>
lo       AF_INET6 (10)
		address: <::1>
enp0s3   AF_INET6 (10)
		address: <fe80::a00:27ff:fe3e:199e%enp0s3>
enp0s8   AF_INET6 (10)
		address: <2001:1310:8122:2::1>
enp0s8   AF_INET6 (10)
		address: <fe80::a00:27ff:fe3e:199f%enp0s8>
```

**Comment by treysis** [comment]
Yup. I've tried that example. I just can't figure out how to access this from mate-applets/netspeed i.e. the `DevInfo` struct.

**Comment by rbuj** [comment]
https://github.com/mate-desktop/mate-applets/blob/7363693872c492c084e52de797126c7f887a16a1/netspeed/src/backend.c#L250

Here you can get all IPv6 addresses using `devinfo->name` instead of getting just one.
```C
...

if (!strcmp (ifa->ifa_name, devinfo->name) {
    s = getnameinfo (ifa->ifa_addr, sizeof(struct sockaddr_in6), host, NI_MAXHOST, NULL, 0, NI_NUMERICHOST);
    g_string_append_printf (addresses6, "%s\n", host);
}
```

**Comment by lukefromdc** [comment]
Note that in testing this, tooltips don't show up on a bottom panel with several applets, this one included:
https://github.com/mate-desktop/mate-panel/issues/1180
