### ISSUE TITLE
autogen.sh doesn't check for autopoint-dependency

### ISSUE THREAD

**Issue by treysis** [mate-desktop/mate-applets#583]
#### Expected behaviour

Should notify user of missing dependency `autopoint`.

#### Actual behaviour

`./autogen.sh` fails with error without meaningful message.

#### Steps to reproduce the behaviour

Run `./autogen.sh` without having `autopoint` installed.

#### MATE general version

Current development snapshot.

**Comment by rbuj** [comment]
Internationalization of packages is optional, so autopoint can't be mandatory.
https://www.gnu.org/software/gettext/manual/html_node/lib_002fgettext_002eh.html

**Comment by treysis** [comment]
Alright. Then this should/could be handled somehow? E.g. disable internationalization if no autopoint, or check for internationalization support and fail with meaningful error only if configured?

**Comment by raveit65** [comment]
Thanks for the reminder. I will add this as `require` to mate-common in fedora. It is missing there.
https://src.fedoraproject.org/rpms/mate-common/blob/master/f/mate-common.spec#_11
mate-common is a developer package and it should install all basic packages to build MATE desktop, IHMO.
From my point of view as fedora maintainer it is a distro packager issue to do it not ;)

**Comment by rbuj** [comment]
Anyway, a warning message is already displayed when the autopoint is not found.
```
$ LANG=C autoreconf --install
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
```
