### ISSUE TITLE
mate-volume-control-applet _snd_ctl_pipewire_open()] error

### ISSUE THREAD

**Issue by moozhub** [mate-desktop/mate-applets#606]
#### Expected behaviour

No spam in system log

#### Actual behaviour

Spam

#### Steps to reproduce the behaviour

Disable pipewire (systemctl --user disable pipewire pipewire.socket)

#### MATE general version

mate-desktop-1.24.1-2.fc32.x86_64

#### Package version

mate-applets-1.24.1-1.fc32.x86_64

#### Linux Distribution

Fedora release 32 (Thirty Two)

#### Link to bugreport of your Distribution (requirement)

https://bugzilla.redhat.com/show_bug.cgi?id=1934054

**Comment by raveit65** [comment]
I can't reproduce this. I have masked pipewire.service/socket in f32.
```
[rave@mother ~]$ Lang=C
[rave@mother ~]$ uname -r
5.10.18-100.fc32.x86_64
[rave@mother ~]$ systemctl --user status pipewire.service pipewire.socket 
● pipewire.service
     Loaded: masked (Reason: Unit pipewire.service is masked.)
     Active: inactive (dead)

● pipewire.socket
     Loaded: masked (Reason: Unit pipewire.socket is masked.)
     Active: inactive (dead)
[rave@mother ~]$ su
Passwort: 
[root@mother rave]# journalctl -b0 -g mate-volume-control
-- Logs begin at Wed 2020-10-21 12:59:12 CEST, end at Tue 2021-03-02 16:36:12 CET. --
-- No entries --
[root@mother rave]# 
```
Disabling a systemd service doesn't mean that it can't start by another service. You need to mask pipewire or pulseaudio when you only use alsa.

**Comment by raveit65** [comment]
Learning systemd = no spam in logs :)

**Comment by moozhub** [comment]
No need to duplicate efforts here... I added additional information to the redhat bug ticket..
