### ISSUE TITLE
Sticky notes should use symbolic icons for close and resize 

### ISSUE THREAD

**Issue by ahayzen** [mate-desktop/mate-applets#608]
#### Expected behaviour

Sticky notes should use symbolic icons for close and resize.

#### Actual behaviour

Sticky notes uses dark icons, so then with a dark theme the icon cannot be seen easily.

#### Steps to reproduce the behaviour

Switch to a dark theme (eg Yaru-MATE-Dark) then open a note and observe that the close and resize icons are dark.

Dark theme
![image](https://user-images.githubusercontent.com/3669750/123343205-3dbc1f80-d549-11eb-8963-fd9907267fe9.png)

Light theme
![image](https://user-images.githubusercontent.com/3669750/123343226-457bc400-d549-11eb-81ef-a96bfbbc0779.png)

#### MATE general version

1.24

#### Package version

1.24.1-0ubuntu1

#### Linux Distribution

Ubuntu 21.04

#### Link to bugreport of your Distribution (requirement)

See the yaru bug for more analysis and the resultant suggestion of using symbolic icons. https://github.com/ubuntu/yaru/issues/2754

**Comment by lukefromdc** [comment]
This is actually a theming issue: themes can force or refuse the use of symbolic icons, and when normal icons (the usual standard in MATE are used) not all icon themes will be compatable with all GTK themes. This is why an overall theme will often include both GTK and icon themes.

**Comment by Feichtmeier** [comment]
Hi there 😁 just a little question, are the icons in this app symbolics (vector SVG) or full colour (PNG)?

**Comment by lukefromdc** [comment]
MATE has never used symbolic icons that I know of (though there is no reason vector SVG cannot be used in a normal colored icon), and has always used full color icons. Symbolic icons were not introduced by GNOME until after GNOME 3 came out, and MATE is the continuation of GNOME 2, which thus predates all use of symbolic icons.

**Comment by Feichtmeier** [comment]
Okay, we have a pending PR for this with a huge lot of work about legacy from colour action icons. Eventually this is tackled there too

CC @ubuntujaggers

**Comment by zhuyaliang** [comment]
@Feichtmeier Can this be closed?
