### ISSUE TITLE
"Windown List" has quit unexpectedly

### ISSUE THREAD

**Issue by gadefox** [mate-desktop/mate-applets#612]
I'm using built from source version 1.26 and everything works fine except this. Also "Window selector", "Workspace switcher" and "Show desktop" applets crash at the same time.. I can't find anything strange in Xsession-errors logs. I'm using Debian 11. I'd like to turn the verbose mode on, so I can check missing config/lib/etc. etc.

**Comment by lukefromdc** [comment]
Window list is part of mate-panel, not mate-applets, it is part of the wncklet applet package in mate-panel.  We have another report of that at 
https://github.com/mate-desktop/mate-panel/issues/1246
closing this as wrong package, discussion can continue on the other report

**Comment by gadefox** [comment]
Okay, I just closed this issue, feel free to reopen it..
