### ISSUE TITLE
CPUFreq: User adjust upper and lower bounds

### ISSUE THREAD

**Issue by WuShufei** [mate-desktop/mate-applets#643]
#### Expected behaviour

CPUFreq is certainly handy, and seems to be working on Raspad running Ubuntu Mate for Raspberry PI 4b.  The manual bounds for it are .6 to 1.5 MHh.

Could this please be adjusted by the user to lower or raise these frequency bounds?  It helps to be able to underclock or over as needed.

Thanks.

**Comment by lukefromdc** [comment]
Those bounds are set by BIOS/UEFI variables. While userspace "overclocking" programs can write to them on some boards, this is hardware specific and beyond the scope of this applet. Note also that when the kernel reports the wrong speeds (as it does when the baseclock is changed as one way of overclocking circa-2010 AMD Athlon and Phenom chips), the applet displays the "wrong" data but this is not the applet's fault.

**Comment by WuShufei** [comment]
Raspi 4B’s BCM2711 can be set from cpuFreq config files to above and below these reported bounds.  I’ve done so from RaspiOS down to .2mhz, but it needs rebooting.  The applet does well in handling this scaling “hot” on the 4B in Raspad.  I’m not deft enough to know how to do this on my ownsie yet.  But it would be very handy for tablets and other pi applications like reduced power remote nodes if an applet could push these lower and higher on the fly.  If any dear reader knows how, perhaps with a fork, please let me know.

**Comment by lukefromdc** [comment]
Those bounds are not set in normal userspace apps but by the kernel and firmware.
The upper bound of course changes when overclocking in BIOS or by specialized
programs that can write to BIOS/UEFI stored variables. Note that some methods
of overclocking (notably changing base clock in older AMD Athlon/Phenom boards)
will not be reported by the kernel as changed CPU speeds though all speeds will
in fact be changed by changing the base clock

**Comment by WuShufei** [comment]
Thanks for the clarification.  Ahhh, so the applet just reads those from BIOS via kernel.  ‘Tis a pity!  I’ll keep looking for a way.
