### ISSUE TITLE
cpufreq-selector - privileges 

### ISSUE THREAD

**Issue by markd89** [mate-desktop/mate-applets#646]
Hi,

I'd like to be able to set the CPU to conservative or performance without needing to enter my password. I was hacking on this a few weeks ago and didn't find a solution. Can someone point me to what works for them? I am using Mate 1.26 in Debian Bookworm (testing)

Thank you!

**Comment by lukefromdc** [comment]
When polkit is in use creating this file should do it:
/var/lib/polkit-1/localauthority/50-local.d/org.mate.cpufreqselector.pkla
with the  oontents below, for users with sudo authority and w/o having the enter your
passphrase.
```
[org.mate.cpufreqselector]
Identity=unix-group:adm
Action=org.mate.cpufreqselector
ResultAny=no
ResultInactive=no
ResultActive=yes
```
I did this so long ago I have forgotten the details of how it works but this is what I have

**Comment by markd89** [comment]
Much thanks, I used this with
Identity=unix-group:users

and it works nicely
