### ISSUE TITLE
[Feature Request] Allow display scaling in monitor-preferences to have values between 100% and 200%

### ISSUE THREAD

**Issue by m007x** [mate-desktop/mate-applets#666]
[Control Centre > Displays]

I think it will be a nice feature to have scaling values between 100% and 200%. 
Examples of this are: 100% 125% 150% and 200%.

**Comment by lukefromdc** [comment]
That is fractional scaling and is quite complicated to implement in x11. All monitor-preferences
is is a frontend to xrandr. I think GTK4 supports (at least to some extent) fractional scaling but
I am not sure. GTK3 either does not or it is very limited, again not sure. To be able to do this
from monitor-preferences, the value passed to Xrandr would have to get usable results.

Fractional scaling does  work fine in wayland at least with the wayfire compositor.
