### ISSUE TITLE
drivemount applet shows no icon (empty button) for certain drives

### ISSUE THREAD

**Issue by MightyPork** [mate-desktop/mate-applets#67]
The drivemount applet works for one of my usb sticks and shows a disk icon, but for another one all I get is a tiny gray button with no icon.

Left-click menu works fine on it, but it looks real bad and it's pain to aim for it with mouse.

See the attached screenshot for details.

![drivemount-applet-bugs](https://f.cloud.github.com/assets/2041118/1707333/0e586fec-60fc-11e3-8880-1bb491fb2189.png)

I don't know where the icons are taken from, but something about that routine is definitely wrong.

**Comment by monsta** [comment]
I guess it's fixed in current version.
