### ISSUE TITLE
GTK3 weather applet: text displays under the icon

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-applets#88]
here a sscreenshot with latest BlueMenta commits from 2014.05.12.
![panel](https://cloud.githubusercontent.com/assets/961604/2939921/d710ec4c-d961-11e3-8d32-b4ec1e35b0bb.png)

**Comment by monsta** [comment]
Fixed by https://github.com/mate-desktop/mate-applets/pull/133.
